### ISSUE TITLE
ODHack: Analyze liquidators

### ISSUE THREAD

**Issue by lukaspetrasek** [CarmineOptions/derisk-research#110]
"Analyze the behavior of liquidators. 

Steps: 
1) Load a sample of events from [the Google Storage](https://storage.googleapis.com/derisk-persistent-state/) for each of the following protocols: "zklend", "nostra_alpha", "nostra_mainnet", "hashstack_v0", and "hashstack_v1". You can find the sample e.g. for zkLend here: [https://storage.googleapis.com/derisk-persistent-state/zklend_data/events_sample.parquet](https://storage.googleapis.com/derisk-persistent-state/zklend_data/events_sample.parquet). To obtain the sample for other protocols, just change the folder in the address, e.g. https://storage.googleapis.com/derisk-persistent-state/nostra_alpha_data/events_sample.parquet for Nostra Alpha. Write the loading part in a way that the source can be easily changed from the Google Storage to a local database.
2) Identify only liquidation events. Use Starkscan to explore their structure. For example, [this is one of zkLend's liquidation events](https://starkscan.co/event/0x00a1e829fb091f7493c509135992ac12af6a81177e3ffab5c34951fb29c23084_6).
3) Identify the amounts of debt tokens liquidated.
4) Visualize the behavior of all liquidators found in the sample in a Jupyter notebook. You should use the visualizations to answer the following questions:
- How many liquidators are there per protocol? Do some of them operate on more than just a single lending protocol?
- How many loans has each of them liquidated?
- What is the average liquidated debt amount? Compute the averages across all liquidations, but also per protocol and per token amounts. 
- What is the total amount of the liquidated debt? Compute the total amounts across all liquidations, but also per protocol and per token amounts. 
- Fetch prices for these tokens (in USD), e.g., from Coingecko. Multiply the token amounts by the corresponding prices to obtain USD nominal amounts and be able to compare the per token stats across tokens.
- [Optional] Analyze the amounts of collateral tokens liquidated (tokens that the liquidator receives) for extra points 🥇 Compute e.g. some stats for the USD difference between the liquidated debt tokens and received collateral tokens, i.e. the liquidators profit.
- Feel free to come up with your own questions, metrics, hypotheses and visualizations."

**Comment by petersdt** [comment]
hi @lukaspetrasek can i work on this it will take me 2 working days.

**Comment by james001-c** [comment]
hi @lukaspetrasek

**Comment by martinvibes** [comment]
hey @lukaspetrasek can I participate in this

**Comment by lukaspetrasek** [comment]
Hi, assigning @james001-c  , because this task is not simple and they provided a better description of the approach.

@james001-c  Let me know if everything is clear and whether you'll be working on the issue. If you have any questions, please ask here. Since this task is quite complex, we can even schedule an introductory call. What is you TG handler please? 🙏🏼 

Consider joining our [TG group](https://t.me/derisk_dev).
See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

**Comment by james001-c** [comment]
> Hi, assigning @james001-c , because this task is not simple and they provided a better description of the approach.
> 
> @james001-c Let me know if everything is clear and whether you'll be working on the issue. If you have any questions, please ask here. Since this task is quite complex, we can even schedule an introductory call. What is you TG handler please? 🙏🏼
> 
> Consider joining our [TG group](https://t.me/derisk_dev). See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

@lukaspetrasek kindly  reassign me this task my touchscreen mistakenly unassigned me. Thanks
my TG handle is: James Nolson 

I joined the TG group already

**Comment by lukaspetrasek** [comment]
Hi @james001-c , do you plan to finish the task?

**Comment by lukaspetrasek** [comment]
Hi @james001-c , unassigning you, because it looks like you've stopped working on this.

**Comment by adrianvrj** [comment]
Hi @lukaspetrasek can I work on this?
It will probably take 3-4 working days!

What I am planning to do is the following:

- Load the data from GCS.
- Analyze the code (I already have some experience with this code ;) )
- Visualize and analyze the data very carefully.
- Treat and answer each question one by one.

**Comment by james001-c** [comment]
hi @lukaspetrasek i am still working on this currently and am making a pr soon to implement request made on the previous PR and address the questions updated above. would really appreciate it if am reassigned it will take me 40hrs from now to make a PR if am reassigned.

**Comment by ManvithaMolakala** [comment]
Hi, I'd like to take this task based on our discussion on TG.

**Comment by lukaspetrasek** [comment]
Hi guys , we've already agreed with @ManvithaMolakala before via TG. She will take this task now 😉
