### ISSUE TITLE
ODHack: Distinguish available liquidity per swap AMM

### ISSUE THREAD

**Issue by lukaspetrasek** [CarmineOptions/derisk-research#111]
Distinguish parts of the available liquidity coming from different swap AMMs.

Steps:
1) Check out the current implementation of fetching available liquidity from Uniswap V2 AMMs: [https://github.com/CarmineOptions/derisk-research/blob/master/src/swap_amm.py#L369](https://github.com/CarmineOptions/derisk-research/blob/master/src/swap_amm.py#L369).
2) Currently, the liquidity from all AMMs is mixed together. Adjust the code so that we're able to distinguish between the liquidity available, e.g., on MySwap, SithSwap, JediSwap, or 10kSwap.
3) Save the adjusted data to a new file on the Google Storage.
4) Visualize available liquidity from different swap AMMs on the main chart on the dashboard. Run `make app` to validate the changes locally.

**Comment by petersdt** [comment]
@lukaspetrasek can i work on this?

**Comment by adrianvrj** [comment]
Hi, can I tackle this one, I think I can deliver it in 2-3 days

Here is how I would approach it

- Review the Current Implementation:
Review the code in the repo and study how it works

- Adjust Code to Distinguish Liquidity:

Modify the code to include functionality that distinguishes liquidity from different swap AMMs.
This might involve adding identifiers for different AMMs and organizing the liquidity data accordingly.

- Save Adjusted Data to Google Storage:

Once the code is adjusted, save the modified data to a new file on Google Storage.
Ensure that the data is structured in a way that makes it easy to distinguish between liquidity from different AMMs.

- Visualize Liquidity on Dashboard:

Integrate the adjusted data into the main chart on the dashboard.
Update the visualization to clearly display liquidity from different swap AMMs.
Run make app to validate the changes locally and ensure that the visualization is working correctly.

**Comment by lukaspetrasek** [comment]
Hi, assigning @adrianvrj , both of you provided a good description of the approach, but @petersdt is already assigned to another task and we prefer to have 1 task per assignee.

@adrianvrj    Let me know if everything is clear and whether you'll be working on the issue. If you have any questions, please ask here. Since this task is quite complex, we can even schedule an introductory call. What is you TG handler please? 🙏🏼 

Consider joining our [TG group](https://t.me/derisk_dev).
See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

**Comment by adrianvrj** [comment]
Thank you @lukaspetrasek I will deliver this asap!
