### ISSUE TITLE
ODHack: Distinguish liquidable debt per lending protocol

### ISSUE THREAD

**Issue by lukaspetrasek** [CarmineOptions/derisk-research#112]
"Distinguish parts of the liquidable debt coming from different lending protocols.

Steps:
1) Check out the current implementation of computing liquidable debt for each lending protocol: [https://github.com/CarmineOptions/derisk-research/blob/master/update_data.py#L89](https://github.com/CarmineOptions/derisk-research/blob/master/update_data.py#L89).
2) Currently, the liquidable debt from all lending protocols is mixed together. Adjust the code so that we're able to distinguish between the liquidable debt, e.g., on zkLend, Hashstack V1, or Nostra Mainnet.
3) Save the adjusted data to a new file on the Google Storage.
4) Visualize liquidable debt from different lending protocols on the main chart on the dashboard. Run `make app` to validate the changes locally.  "

**Comment by NueloSE** [comment]
hi @lukaspetrasek  can i jump on this task

**Comment by petersdt** [comment]
hi @lukaspetrasek can i work on this. it will take me 2 working days to finish this task
steps to t

**Comment by lukaspetrasek** [comment]
Hi, assigning @petersdt  , because this task is not simple and they provided a better description of the approach.

@petersdt   Let me know if everything is clear and whether you'll be working on the issue. If you have any questions, please ask here. Since this task is quite complex, we can even schedule an introductory call. What is you TG handler please? 🙏🏼 

Consider joining our [TG group](https://t.me/derisk_dev).
See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

**Comment by ManvithaMolakala** [comment]
Hi. Can I take up this issue if noone else is working on this?

It would take me 3-4 working days to finish the task. 

My approach:
1. I will take a look into deeper logic on how liquidable debt is computed and make necessary modifications in src and update data files.
2. ⁠I think Hashstack files may need some work. So will focus there first.
3. Then save the updated data to google dataset 
4. Update the main chart file to visualise liquidable debts from different protocols 
5. Run "make app" to ensure output works fine
