### ISSUE TITLE
ODHack: Make it easier to sum 2 Portfolio instances

### ISSUE THREAD

**Issue by lukaspetrasek** [CarmineOptions/derisk-research#113]
Adjust the Portfolio class so that two of its instances can be summed together, resulting in a portfolio containing tokens from both summed portfolios. The Portfolio class is implemented here: [https://github.com/CarmineOptions/derisk-research/blob/master/src/helpers.py#L78](https://github.com/CarmineOptions/derisk-research/blob/master/src/helpers.py#L78).

**Comment by adrianvrj** [comment]
Hi can I hop on this?

**Comment by lindsaymb15** [comment]
Hi! @lukaspetrasek I would like to take this task. I estimate no more than 2 days for the changes to be ready.
This would be my first issue on this project, but I have experience working with python. The proposed approach would be to implement a custom add method in the class, which will create a new instance of Portfolio with he combined tokens.

**Comment by lindsaymoralesb** [comment]
Hi! @lukaspetrasek I would like to take this task. I estimate no more than 2 days for the changes to be ready.
This would be my first issue on this project, but I have experience working with python. The proposed approach would be to implement a custom add method in the class, which will create a new instance of Portfolio with he combined tokens.

**Comment by lukaspetrasek** [comment]
Hi, assigning @lindsaymoralesb  , because they provided a better description of the approach and lower ETA.

@lindsaymoralesb  Let me know if everything is clear and whether you'll be working on the issue. If you have any questions, please ask here. What is you TG handler please? 🙏🏼 

Consider joining our [TG group](https://t.me/derisk_dev).
See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

**Comment by lindsaymoralesb** [comment]
Thanks! Yes, I’ll be working on this.
Already joined the group, my tg is @lindsaymorales. Will let you know if I have any doubts.

**Comment by lindsaymoralesb** [comment]
hey @lukaspetrasek ! so the changes are already in [this PR](https://github.com/CarmineOptions/derisk-research/pull/116).
I just had a question on how I could test this new feature of adding two portfolios, I tested the code outside to make sure it will work, but I was wondering if there was a way of testing it on the project just to double check!

**Comment by lukaspetrasek** [comment]
Hi, added 1 comment 😉

**Comment by lukaspetrasek** [comment]
Hi @lindsaymoralesb , few more simple comments.

**Comment by lindsaymoralesb** [comment]
Hey! @lukaspetrasek did you leave them on the PR? I can’t find them

**Comment by lukaspetrasek** [comment]
> Hey! @lukaspetrasek did you leave them on the PR? I can’t find them

Oh shoot, forgot to submit them. Now it's done.

**Comment by lindsaymoralesb** [comment]
No worries! Changes are ready for review.
