### ISSUE TITLE
ODHack: Fetch historical interest rates for Hashstack

### ISSUE THREAD

**Issue by lukaspetrasek** [CarmineOptions/derisk-research#114]
Fetch data on historical interest rates for deposits and debt for the Hashstack lending protocol.

Steps:
1) Explore possibilities/sources for obtaining data for Hashstack interest rates (e.g. chain data, API, SDK).
2) Fetch historical interest rates for deposits and debts separately. The data should be timestamped and labeled by the block number. Fetch data for the following tokens: ""ETH"", ""wBTC"", ""USDC"", ""DAI"", ""USDT"", ""wstETH"", ""LORDS"", ""STRK"", ""UNO"" and ""ZEND"".
3) Save the data in a database. The suggested columns are `protocol` (str), `block` (int), `timestamp` (int), `token_address` (str), `cumulative_interest_rate` (int).
4) Write a script that periodacially fetches and saves the data every 15 minutes (parameter). Dockerize it.

**Comment by adrianvrj** [comment]
Hi, can I work on this?

I think I could finish this in 2-3 days

Here is how I would approach it

Sure, here's a step-by-step solution:

Explore Data Sources:
   - Research available sources for historical interest rates for deposits and debts in the Hashstack lending protocol. This could include chain data, APIs, or SDKs provided by Hashstack or other platforms.

Fetch Historical Interest Rates:
   - Write code to fetch historical interest rates for deposits and debts separately. Ensure the data is timestamped and labeled by the block number.
   - Fetch data for the specified tokens: "ETH", "wBTC", "USDC", "DAI", "USDT", "wstETH", "LORDS", "STRK", "UNO", and "ZEND".
Save Data in a Database:
   - Create a database schema with the suggested columns: protocol (string), block (integer), timestamp (integer), token_address (string), cumulative_interest_rate (integer).
   - Store the fetched data in the database using appropriate database operations.

Write Periodic Script:
   - Write a script that periodically fetches and saves the data. You mentioned a parameter of every 15 minutes, so ensure the script fetches data at that interval.
   - Incorporate error handling and logging to ensure robustness.
   
Dockerize the Script:
   - Containerize the script using Docker to ensure portability and ease of deployment.
   - Write a Dockerfile that includes all necessary dependencies and instructions for running the script inside a Docker container.

**Comment by danielcdz** [comment]
Hello @lukaspetrasek I think I can take this one! It will take me about 2 or 3 days to complete!

**Comment by martinvibes** [comment]
hi @lukaspetrasek can I hopefully participate on this

**Comment by Naveenkhasyap** [comment]
Hey @lukaspetrasek ,

Can I take this task, 
1. will identify the source to scrape Hash stack interest rates 
2. Will fetch Historical data for  deposits and debts separately 
3. As I have checked the repo we are using Postgres DB if am not wrong you want us to save data in this DB in one of the table.
4.  we can run a cron parallel to fetch data at given timeframe.

Timeline wise will take 2 days to plan and write code and test this.

**Comment by more-of-odeh** [comment]
Hi @lukaspetrasek can I be assigned this talk? This is my first contributing  and I would love to proof my acquired skill.

**Comment by lukaspetrasek** [comment]
Hi, assigning @Naveenkhasyap  , because this task is not easy and they provided a better description of the approach and also lower estimate of the MDs that would take to solve it.

@Naveenkhasyap  Let me know if everything is clear and whether you'll be working on the issue. If you have any questions, please ask here. What is you TG handler please? 🙏🏼 

Consider joining our [TG group](https://t.me/derisk_dev).
See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

**Comment by Naveenkhasyap** [comment]
Hi @lukaspetrasek , thanks, am already active in your TG group will be asking queries there handle is @NaveenKashyap

**Comment by Josh-121** [comment]
would love to contribute if still available

**Comment by lukaspetrasek** [comment]
> would love to contribute if still available

Hi, it's not available. @Naveenkhasyap is taking care of this issue 😉

**Comment by lukaspetrasek** [comment]
Hi @Naveenkhasyap , I have to unassign you, because you haven't committed anything and this is blocking the development of other features.

**Comment by Josh-121** [comment]
Hello. Can I be assigned now?

**Comment by faurdent** [comment]
Hi, I would like to take this one, I have experience with on-chain and I'm already familiar with codebase of Derisk
My next steps will be:
1. Fetch data for Hashstack
2. Grouped and calculated interest rate
3. Store it to db

**Comment by lukaspetrasek** [comment]
Hi, assigning @faurdent , because this task is not easy and they provided a better description of their approach.
