### ISSUE TITLE
ODHack: Fetch parameters for zkLend dynamically in `data_handler`

### ISSUE THREAD

**Issue by lukaspetrasek** [CarmineOptions/derisk-research#115]
Fetch zkLend's token parameters dynamically.

Steps:
1) Check out the static settings for the zkLend lending protocol: [https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handlers/loan_states/zklend/settings.py#L23](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handlers/loan_states/zklend/settings.py#L23).
2) Currently, the token parameters are static, but in reality, they change once in a while. Adjust the code so that we're able to fetch the current/latest parameters dynamically from chain.
3) Adjust all references of the original static settings, so that the static settings are no longer needed.

**Comment by EmmanuelAR** [comment]
Hey can i work on this?

**Comment by lukaspetrasek** [comment]
Okay, assigning you @EmmanuelAR  . But note that the OD Hackaton tasks should be finished by the end of the week 🙏🏼 

@EmmanuelAR   Let me know if everything is clear and whether you'll be working on the issue. If you have any questions, please ask here. What is you TG handler please? 🙏🏼 

Consider joining our [TG group](https://t.me/derisk_dev).
See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

**Comment by EmmanuelAR** [comment]
Excellent I will stray today and let u know if I have a question

**Comment by EmmanuelAR** [comment]
Hello team, yesterday @lukaspetrasek  asssigme this issue to me, thanks for that. 

As soon that i read the issue i uderstand to make a method to fetch ZKLEND_SPECIFIC_TOKEN_SETTINGS info and not mantain it static.

<img width="899" alt="Captura de pantalla 2024-05-29 a la(s) 10 03 58 a  m" src="https://github.com/CarmineOptions/derisk-research/assets/54730752/34b788bb-550e-460a-86dd-158d854eccb1">

Did someone knows where did a can make that call on chain to have that info?
If theres an example of how to make that call?

**Comment by lukaspetrasek** [comment]
Answered on TG.

**Comment by Josh-121** [comment]
willing to work on this issue, I have an understanding to write a call to fetch the required data and replace the static ones. Will be done in few hours

**Comment by EmmanuelAR** [comment]
Pr: #121

**Comment by lukaspetrasek** [comment]
> Pr: #121

Thanks, I'll take a look over the weekend.

**Comment by EmmanuelAR** [comment]
#121
