### ISSUE TITLE
Add a table with cumulative liquidable debt to the dashboard

### ISSUE THREAD

**Issue by lukaspetrasek** [CarmineOptions/derisk-research#187]
Steps:

0) Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
1) Check out the current implementation of our streamlit dashboard, specifically the part that displays the main chart titled "Liquidable debt and the corresponding ...": [https://github.com/CarmineOptions/derisk-research/blob/master/app.py#L319](https://github.com/CarmineOptions/derisk-research/blob/master/app.py#L319). The dashboard can be found [here](https://starknet.derisk.carmine.finance/).
2) Below the warning under the main chart, display a table showing the cumulative liquidable debt for each price level. Note that the debt should accumulate with the decreasing price, i.e. the lowest price will observe the largest cumulative debt, and vice versa.

**Comment by ShantelPeters** [comment]
Please I’ll like to work on this issue

**Comment by dev-chinx** [comment]
hello @dmirgaleev please can i work on this issue :) and would love to be a contributor

**Comment by Josue19-08** [comment]
@lukaspetrasek I would like to take this task. I plan to start on September 27th and complete it by October 3rd. I have experience in Python, Streamlit, data analysis, visualization with Plotly, API integration, frontend development, and I am comfortable working on dashboard projects like this.

**Comment by ooochoche** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
@lukaspetrasek

### How I plan on tackling this issue
I'm ready to take on this task! After reviewing the guidelines, README, and current implementation, I have a strong understanding of what's needed.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
hello @lukaspetrasek can I work on this. I will soo love to work on this issue

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Hello @lukaspetrasek  I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute

### How I plan on tackling this issue
I will ensure that the dashboard has a display with the with cumulative liquidable debt on the dashboard by foollowing the outlined steps. here i should complete this in 2-3 days

**Comment by thesledge04** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Proficient in Python and Streamlit, enabling me to efficiently work on the existing dashboard and implement the necessary calculations and visualizations. Experience in handling financial data and calculating cumulative metrics, ensuring the implementation accurately reflects the desired logic for accumulating debt based on price levels. Familiarity with best practices for data presentation in web applications, allowing me to enhance the user experience by ensuring the table is clear and easy to interpret.

### How I plan on tackling this issue
Approach to Display Cumulative Liquidable Debt Table:
Understand Current Chart Implementation:

Review the section around line 319 in app.py, which displays the main chart for "Liquidable debt and the corresponding supply."
Ensure that we have access to the debt data at each price level to accumulate it.
Calculate Cumulative Debt:

For each price level, calculate the total liquidable debt by summing up the debts for all lower or equal price levels (accumulating with decreasing price).
Create a cumulative debt calculation function:
def calculate_cumulative_debt(debt_data):
    cumulative_debt = []
    total_debt = 0
    for price, debt in sorted(debt_data, reverse=True):  # Sort by price, descending
        total_debt += debt
        cumulative_debt.append((price, total_debt))
    return cumulative_debt
Display Cumulative Debt in a Table:

Use Streamlit's st.table() or st.dataframe() to display the cumulative debt alongside the price levels.
Example:

cumulative_debt = calculate_cumulative_debt(debt_data)
st.table(cumulative_debt)  # Or st.dataframe for more dynamic tables
Position Table Below the Warning:

Locate the position below the warning under the chart and add the table there to show cumulative debt for each price level.
Example of placement:

st.warning("Some informative warning here")
st.table(cumulative_debt)  # Display the cumulative debt table below the warning
Test and Verify:

Run the updated dashboard locally to ensure the cumulative debt is accurately calculated and displayed in a clear, readable format.

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.


### How I plan on tackling this issue
Define Cumulative Liquidable Debt Calculation
Determine the formula for calculating cumulative liquidable debt:
Sum of debt across all loans
Filter by liquidable status
Consider interest rates, loan terms, and collateral values
Gather Required Data
Collect necessary data for calculation:
Loan data (amount, interest rate, term, collateral value)
Liquidation status
User debt history

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
i am a blockchain developer and this would be my first time contributing to this ecosystem . i am avaliable to work 

### How I plan on tackling this issue
To approach this issue, i will  start by reviewing the Contributor Guidelines and README for any specific requirements or coding standards. Next, examine the current implementation of the Streamlit dashboard, focusing on the section that displays the main chart titled "Liquidable debt and the corresponding ...". 

Once i understand how the chart is generated, implement a new table below the chart that displays the cumulative liquidable debt for each price level. Ensure that the table reflects the accumulation of debt in accordance with the specified price levels, with the lowest price showing the largest cumulative debt. Test the changes to verify that the data displays correctly and integrates seamlessly with the existing dashboard.

**Comment by lukaspetrasek** [comment]
Hi everyone, assigning @josephchimebuka!

@josephchimebuka Let me know if everything is clear. If you have any questions, please ask here. What is you TG handler please? 🙏🏼 

Consider joining our [TG group](https://t.me/derisk_dev).
See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).
