### ISSUE TITLE
Handle missing environment variables PG_CONNECTION_STRING and CREDENTIALS_PATH

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#200]
## Task Description

Handle missing env variables while set up the project and up and running to pretend most common issue with set up the project.

## Steps

1. Review our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md)

2. Set up the project and create a new branch:
   • Fork this repository.
   • Create a new branch for your work.

3. Install the project [installation guide](https://gist.github.com/djeck1432/cd3ea7ecc0f71b44ec4db5b1f30c4574)
4. Handle missing `PG_CONNECTION_STRING` and `CREDENTIALS_PATH`. If you not export these variables, the charts can't be rendered. So we would like to handle this case.

## Hints:
You can find settings there env variables here:
1. [PG_CONNECTION_STRING](https://github.com/CarmineOptions/derisk-research/blob/master/src/db.py#L8)
2. [CREDENTIALS_PATH](https://github.com/CarmineOptions/derisk-research/blob/master/src/helpers.py#L155)

**Comment by Gift-Naomi** [comment]
@djeck1432 can I work on this?

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
hello i would love to work on this issue

### How I plan on tackling this issue
Review Contributor Guidelines and README.
Fork the repository and create a new branch for your work.
Follow the project installation guide to set up the environment.
Implement error handling for missing PG_CONNECTION_STRING and CREDENTIALS_PATH. Ensure the charts can still render gracefully if these variables are not exported.

**Comment by jaykayudo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
I am a python developer with good web3 experience. i believe i am fit to perform this task based on my experience as a software engineer with 5 years of experience which you can confirm by viewing my profile

### How I plan on tackling this issue
- I will follow the first three steps listed above to make sure i contribute to the project in the correct manner.
- I will create a .env.example file which will be used to direct development on the env variables needed for the project
- I will add a section to the documentation to make sure developers create a .env file from the .env.example file with the following command `cp .env.example .env`
- I will add python-dotenv to the requirements.txt file to ensure the use of the `loadenv()`method of the module for loading the env from the file into the runtime server.
- I will test properly to make sure there is no error and i followed the contribution guideline
- I wil make a PR
