### ISSUE TITLE
Standardize event data for accumulators’ data

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#220]
1.  Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. Parse data from event which fetched on-chain to humman-readable format, for example, now we have `user = data[0]` and we want to have `user = data.user`
 - In method [parse_accumulators_sync_event](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handler_tools/data_parser/zklend.py#L7)
 - Event data structure - [event data](https://starkscan.co/event/0x029628b89875a98c1c64ae206e7eb65669cb478a24449f3485f5e98aba6204dc_0)
3. Create Serializers model using pydantic in [serializers.py](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handler_tools/data_parser/serializers.py)
4. In method [process_accumulators_sync_event](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handlers/loan_states/zklend/events.py#L160C9-L160C40)
substitute fetching data by index `Example: user= data[0]` to `data.user` using serializer class

**Comment by Gerson2102** [comment]
Hey can I work on this one?

**Comment by djeck1432** [comment]
@Gerson2102 Here is an example, how you can test it
https://gist.github.com/djeck1432/7948489d3fed99d6d56ef6c6f86b16bd
