### ISSUE TITLE
Standardize event data for deposit data

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#221]
1.  Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. Parse data from event which fetched on-chain to humman-readable format, for example, now we have `user = data[0]` and we want to have `user = data.user`
 - In method [parse_deposit_event](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handler_tools/data_parser/zklend.py#L12C9-L12C28)
 - Event data structure - [event data](https://starkscan.co/event/0x036185142bb51e2c1f5bfdb1e6cef81f8ea87fd4d777990014249bf5435fd31b_3)
3. Create Serializers model using pydantic in [serializers.py](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handler_tools/data_parser/serializers.py)
4. In method [process_deposit_event](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handlers/loan_states/zklend/events.py#L175C9-L175C30)
 substitute fetching data by index `Example: user= data[0]` to `data.user` using serializer class

**Comment by Josh-121** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Software engineering background, python developer, smart contract developer 

### How I plan on tackling this issue
Using the structure of the event data, make it accessed using dot notation (e.g., data.user).

Define a Pydantic model that reflects the structure of the event data, including attributes like user, amount, etc.

substitute fetching data by index as stated. Work on any feedback & recommendations.
I like oranges

**Comment by djeck1432** [comment]
@Josh-121 Feel free to apply to this issue, once you finish your current task, don't forget that you have 24 hours to open our draft PR

**Comment by martinvibes** [comment]
hello @djeck1432 i would like to work on this issue :)

**Comment by Immanuelolivia1** [comment]
@djeck1432 can i work on this ?

**Comment by od-hunter** [comment]
Hi @djeck1432 , can I work on this?

**Comment by od-hunter** [comment]
Hi @djeck1432 , can I be assigned this?
I like oranges

**Comment by Josh-121** [comment]
> @Josh-121 Feel free to apply to this issue, once you finish your current task, don't forget that you have 24 hours to open our draft PR
Done ser

**Comment by djeck1432** [comment]
@Immanuelolivia1 You didn't create draft PR, during 48 hours, you will be unassigned from this issue.

**Comment by od-hunter** [comment]
Hi @djeck1432 , please can I be assigned this?
'I would like to take this task, I love 🍍

**Comment by Benjtalkshow** [comment]
Can i be assigned to this issue. I am ready to start working on it. ETA 48hrs
