### ISSUE TITLE
Create test cases for `DeRiskAPIConnector`

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#222]
1.  Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. In folder [tests](https://github.com/CarmineOptions/derisk-research/tree/master/data_handler/tests) create test cases for [DeRiskAPIConnector](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handler_tools/api_connector.py#L9C7-L9C25) using unittests
3. Create test cases `DeRiskAPIConnector()` positive when url is set up and negative when url is not set up
4. Create test cases `DeRiskAPIConnector.get_data()` positive when response return some data, negative, when response has error

**Comment by ooochoche** [comment]
Can I work on this

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
hello i would love to work on this issue :)
