### ISSUE TITLE
Standardize event data for liquidation event.

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#223]
1.  Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. Parse data from event which fetched on-chain to humman-readable format, for example, now we have `user = data[0]` and we want to have `user = data.user`
 - In method [parse_liquidation_event](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handler_tools/data_parser/zklend.py#L38)
 - Event data structure - [event data](https://starkscan.co/event/0x07b8ec709df1066d9334d56b426c45440ca1f1bb841285a5d7b33f9d1008f256_5)
3. Create Serializers model using pydantic in [serializers.py](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handler_tools/data_parser/serializers.py)
4. In method [process_liquidation_event](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handlers/loan_states/zklend/events.py#L323C9-L323C34)
 substitute fetching data by index `Example: user= data[0]` to `data.user` using serializer class

**Comment by martinvibes** [comment]
hello @djeck1432 can i work on this issue :)

**Comment by Mystic-Nayy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
I am a web3 developer, I have expertise in smart contracts, decentralized technologies, and frameworks like React. I can build innovative dApps, contribute to open-source projects, educate others, and network with industry leaders to advance my career in the decentralized space.

### How I plan on tackling this issue
I will create a Pydantic model for the event structure in serializers.py, update parse_liquidation_event to parse data into this model, and modify process_liquidation_event to use attribute-based access instead of index-based access for a more readable format.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
I would like to take this task.

I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js, TypeScript, and Python. I’ve made over 25 contributions to over 12 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

### How I plan on tackling this issue

I will set up the project by following the instructions in the `README.md`. I will then work on the `parse_liquidation_event` method to standardize the event data. This involves parsing the on-chain data to a human-readable format, changing how we access the user from `data[0] to data.user`.

Next, I will create a Pydantic serializer model in `serializers.py` to handle this standardized data. In the `process_liquidation_event` method, I will replace the index-based data fetching with the serializer class for better clarity and maintainability. I will ensure my code is well-tested and follows all project guidelines. I try my possible best to make a PR in 48hrs from the start of this hackathon. thanks

**Comment by jaykayudo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
I am a First Principle Engineer, Python developer and software engineer with ample experience in building software application , python application and web3 applications.

### How I plan on tackling this issue
- I will create a Pydantic model to represent the liquidation event data structure
- I will create the following fields in the model: liquidator, user, debt_token, debt_raw_amount, debt_face_amount, collateral_token, collateral_amount.
- I will create field validation appropriately for the field if necessary.
- I will update the process_liquation_event to use the new structure.

**Comment by godekina** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
I am a python developer and a data scientist.

### How I plan on tackling this issue
I am applying to this issue via https://app.onlydust.com/p/derisk


I am familiar with parsing events data therefore I will like to work on this issue, and here is how I will approach it:

1. Understand Event Structure - Identify the fields in the on-chain event.
2. Create Pydantic Serializer -Define a LiquidationEventSerializer class using Pydantic in serializers.py and map the event fields to descriptive names.
3. Parse Event Data- In parse_liquidation_event I will use the Pydantic model to convert index-based data to readable fields.
4. Update Data Access in process_liquidation_event - Replace index-based access with field names.
5. Add validation in the Pydantic model for better data integrity.

**Comment by djeck1432** [comment]
@jaykayudo Here is an example, how you can test it
https://gist.github.com/djeck1432/7948489d3fed99d6d56ef6c6f86b16bd

**Comment by jaykayudo** [comment]
> @jaykayudo Here is an example, how you can test it https://gist.github.com/djeck1432/7948489d3fed99d6d56ef6c6f86b16bd

Okay. On it.
