### ISSUE TITLE
Refactor function call to on-chain

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#226]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. Create class `StarknetClient` with async methods and put all these methods into new class
https://github.com/CarmineOptions/derisk-research/blob/master/shared/blockchain_call.py#L12
3. Create new method `__init__` which will parse url and set it to class variable 
4. create async method `func_call` which can reuse
5. Create asnyc method for `balance_of` which can reuse
6. Create async method for `get_myswap_pool`
7. Please, make sure you have added docsring and annotation types
8. Update all imports and using it in `data_handler` and `dashboard_app` folders where these methods are called:
- `func_call`
- `balance_of`
- `get_myswap_pool`

**Comment by djeck1432** [comment]
@petersdt Sorry, but this is backend task not FE

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Hello, i'm a frontend and blockchain developer, i would to work on this task

**Comment by raizo07** [comment]
Hello @djeck1432 can I be assigned to work on this?

I'm a Blockchain dev with over 4 years experience.

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Am a software developer with experience in building user application using python and linking smart contracts to dapp. 

### How I plan on tackling this issue
based on the above requirement this is a psuedo step by step approach to handle the above task:

i'll create a new class StarknetClient that inherits from BaseChainCall.
i'll implement the __init__ method to parse the URL and set it as a class variable.
i'll create an async method func_call that reuses the existing functionality.
i'll implement an async method balance_of that reuses the existing functionality.
i'll create an async method get_myswap_pool with proper documentation and type annotations.
i'll update the imports in the data_handler and dashboard_app folders.
i'll ensure all methods have proper docstrings and type annotations.

**Comment by djeck1432** [comment]
Guys, this task for backend developer on python, not FE issues
