### ISSUE TITLE
Create mock database and write test cases for CRUD classes

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#227]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. In this [tests](https://github.com/CarmineOptions/derisk-research/tree/master/data_handler/tests) folder, create `confest.py` file where you will mock db connection using `pytest` package
3. Create new folder `db_test` in [tests](https://github.com/CarmineOptions/derisk-research/tree/master/data_handler/tests) folder and add there next files `test_db_connector.py` and `test_initializer_db_connector.py` in these files, create test cases for next classes: 
- [DBConnector](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/db/crud.py#L25)
- [InitializerDBConnector](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/db/crud.py#L25)
4. Please, create negative and positive scenarios. So it should test not only success execution but also raise error to proper handling

**Comment by martinvibes** [comment]
hello @djeck1432 i would love to work on this one

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Hello, i'm a frontend and blockchain developer, i would to work on this task

**Comment by djeck1432** [comment]
@NueloSE @martinvibes Guys, priority for first good issue is always given to newcomers. Just letting you know in case you’re not following us in the Telegram groups.

**Comment by djeck1432** [comment]
@blessingbytes are you sure you can do that, as long as you fe developer not backend?

**Comment by petersdt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
I have an understanding of implement api calls from a database and with it i believe i would be able to handle the create read update and delete operations on the database. 

### How I plan on tackling this issue
- I would connect to the database and make CRUD operation to the database 
- By creating unit test in the db_test/tests/test_db_connector.py and db_test/tests/InitializerDBConnector suitable test cases for DBConnector and initializerDBConnetor function covering several edge cases.

**Comment by petersdt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
I have experience calling api endpoints from frontend and have worked with database before. with this experience i would be able to test create, read, update and delete operations on a database kindly assign me the task

### How I plan on tackling this issue
i would create a db_test/tests/test_initializer_db_connector.py and db_test/tests/test_db_connector.py and test several edge case for the CRUD operations to the database kiindly assign ETA <= 48hrs

**Comment by bruhhgnik** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
I'm nik, a python developer with prior experience in linux and blockchain dev.

### How I plan on tackling this issue
I would love to take on this issue
eta: 2 days at max
