### ISSUE TITLE
Rework SwapAmm class and write test cases

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#228]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. For [SwapAmm](https://github.com/CarmineOptions/derisk-research/blob/master/shared/amms.py#L107) do next things:
 1. Create mapping for `add_pool` values to move it out of the class to another file, like [constants.py](https://github.com/CarmineOptions/derisk-research/blob/master/shared/constants.py)
 ```
  self.add_pool(
            "ETH",
            "USDC",
            [
                "0x04d0390b777b424e43839cd1e744799f3de6c176c7e32c1812a41dbd9c19db6a",  # jediswap
                "0x030615bec9c1506bfac97d9dbd3c546307987d467a7f95d5533c2e861eb81f3f",  # sithswap
                "0x000023c72abdf49dffc85ae3ede714f2168ad384cc67d08524732acea90df325",  # 10kswap
            ],
            1,
        )
```
2. Add to `__init__` method adding all pools from your new mapping 
3. Remove from `init()` method adding pools
4. For each method, please add docstring and annotation types
5. Create new folder, `tests` in [shared](https://github.com/CarmineOptions/derisk-research/tree/master/shared) folder
6. Create for `SwapAmm` test cases with positive and negative scenarios in a new file `test_swap_amm.py`
7. Please, use pytest for creating and running test cases.

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Hello, i'm a frontend and a blockchain developer, i would love to take this task

### How I plan on tackling this issue
I would take a look at the requirement and follow it exactly to make sure that i complete everything and leave no stone unturned.  i would first go through the codebase to understand the project and coding style

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Hello, i'm a frontend and a blockchain developer, i would love to take this task

### How I plan on tackling this issue
I would take a look at the requirement and follow it exactly to make sure that i complete everything and leave no stone unturned.  i would first go through the codebase to understand the project and coding style

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Hello, i'm a frontend and a blockchain developer, i would love to take this task

### How I plan on tackling this issue
I would take a look at the requirement and follow it exactly to make sure that i complete everything and leave no stone unturned.  i would first go through the codebase to understand the project and coding style

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Hello, i'm a frontend and a blockchain developer, i would love to take this task

### How I plan on tackling this issue
I would take a look at the requirement and follow it exactly to make sure that i complete everything and leave no stone unturned.  i would first go through the codebase to understand the project and coding style

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Hello, i'm a frontend and a blockchain developer, i would love to take this task

### How I plan on tackling this issue
I would take a look at the requirement and follow it exactly to make sure that i complete everything and leave no stone unturned.  i would first go through the codebase to understand the project and coding style

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Hello, i'm a frontend and a blockchain developer, i would love to take this task

### How I plan on tackling this issue
I would take a look at the requirement and follow it exactly to make sure that i complete everything and leave no stone unturned.  i would first go through the codebase to understand the project and coding style

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Hello, i'm a frontend and a blockchain developer, i would love to take this task

### How I plan on tackling this issue
I would take a look at the requirement and follow it exactly to make sure that i complete everything and leave no stone unturned.  i would first go through the codebase to understand the project and coding style

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Hello, i'm a frontend and a blockchain developer, i would love to take this task

### How I plan on tackling this issue
I would take a look at the requirement and follow it exactly to make sure that i complete everything and leave no stone unturned.  i would first go through the codebase to understand the project and coding style

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Hello, i'm a frontend and a blockchain developer, i would love to take this task

### How I plan on tackling this issue
I would take a look at the requirement and follow it exactly to make sure that i complete everything and leave no stone unturned.  i would first go through the codebase to understand the project and coding style

**Comment by vijay-kesanakurthi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
I am fullstack developer, i have more than one year of experience in blockchain. I'd like to work on this issue, Could you please assign it to me?

### How I plan on tackling this issue
- Read and follow contributor guidelines
- Follow the steps mentioned in the description and refactor the code in `SwapAmm `.
- Write tests for SwapAmm

**Comment by bruhhgnik** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
I'm nik, a python dev..i have prior experience in blocjchain and linux development.

### How I plan on tackling this issue
I'll reorganize the code by moving the pool data to a sepaarate constants.py file, then modify the SwapAmm class to automatically load these pools when starting up. 
But i would love to interact with the admin for better guidance.

**Comment by bruhhgnik** [comment]
Thanks for the opportunity!

**Comment by djeck1432** [comment]
@bruhhgnik You are unassigned from this issue as long as I don't see any draft PR

**Comment by binayak9932** [comment]
Can I take this issue?

**Comment by od-hunter** [comment]
Can I work on this please? @djeck1432

**Comment by tosoham** [comment]
I would like to take this task, I love 🍍
ETA : 2-3 days

**Comment by Benjtalkshow** [comment]
@djeck1432  Can i work on this asap. ETA 24hrs

**Comment by binayak9932** [comment]
Can I twork on this ?I love 🍍 i have contributed to spotnet i am sure i can help here

**Comment by bruhhgnik** [comment]
> @bruhhgnik You are unassigned from this issue as long as I don't see any draft PR

sir i was already working on this, moreover its been just 2 days since the assignment, was there any specific deadline outside of the ODhack official deadline that i wasn't aware of?

**Comment by djeck1432** [comment]
@Benjtalkshow When you applied, you should have read Contributor guideline, where is written that you have 48 hours for opening draft PR, we can't wait unlimited time, it's hackathon, every task should be done quickly because it can easily block further developing. Everyone created draft PR apart from you and one more contributor. This issues estimated for 8 hours max, so you had more than enough to open draft PR. Please, next time read carefully guideline and follow the rules. Also I posted in telegram channel and asks twice per day to not postpone development and create draft PR as soon as possible.

**Comment by djeck1432** [comment]
@Benjtalkshow On the other hand you were assigned to another issue and worked at the same time on 2 issues, which is not welcome in this project
Proof of my words: https://github.com/keep-starknet-strange/garaga/issues/240#issuecomment-2436353133
So please, next time take one issue and work on it, not take 2 or more issues and wait until deadline is over.
p.s. I checked your github which confirmed my words above. 
so I think this topic is closed. After hackathon I will discuss it with OnlyDust to pretend this case when contributor works at once on 2 or more issues.

**Comment by Benjtalkshow** [comment]
> @Benjtalkshow On the other hand you were assigned to another issue and worked at the same time on 2 issues, which is not welcome in this project Proof of my words: [keep-starknet-strange/garaga#240 (comment)](https://github.com/keep-starknet-strange/garaga/issues/240#issuecomment-2436353133) So please, next time take one issue and work on it, not take 2 or more issues and wait until deadline is over. p.s. I checked your github which confirmed my words above. so I think this topic is closed. After hackathon I will discuss it with OnlyDust to pretend this case when contributor works at once on 2 or more issues.

@djeck1432 
I think you are tagging the wrong person.

**Comment by djeck1432** [comment]
@Benjtalkshow sorry, fixed it
