### ISSUE TITLE
 Standardize event data for enabled/disabled collateral event

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#232]
1.  Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. Parse data from event which fetched on-chain to humman-readable format, for example, now we have `user = data[0]` and we want to have `user = data.user`
 - In method [parse_collateral_enabled_disabled_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/zklend.py#L67)
 - Event data structure enabled collateral - [event data]( https://starkscan.co/event/0x036185142bb51e2c1f5bfdb1e6cef81f8ea87fd4d777990014249bf5435fd31b_6)

 - In method [process_collateral_disabled_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/zklend/events.py#L247)
 - Event data structure disabled collateral - [event data](https://starkscan.co/event/0x0049b445bed84e0118795dbd22d76610ccac2ad626f8f04a1fc7e38113c2afe7_0)
3. Create Serializers model using pydantic in [serializers.py](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/serializers.py)
4. In method [process_collateral_enabled_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/zklend/events.py#L217) and 
[process_collateral_disabled_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/zklend/events.py#L247) substitute fetching data by index `Example: user= data[0]` to `data.user` using serializer class

**Comment by PoulavBhowmick03** [comment]
I would like to take this task, I love 🍍

**Comment by godekina** [comment]
Mind if I try this one?

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other Python projects like:

- `giza-agents`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by PoulavBhowmick03** [comment]
The file structure seems to have changed

**Comment by tosoham** [comment]
Can I work on this? I would like to take this task, I love 🍍
ETA 2days

**Comment by aniruddhaaps** [comment]
I'm a python dev, a new comer here. I want to take up this issue and solve it.

**Comment by djeck1432** [comment]
> The file structure seems to have changed and there are errors in this implementation

Can you text me in telegram please

**Comment by djeck1432** [comment]
> I'm a python dev, a new comer here. I want to take up this issue and solve it.

Please, read guideline first

**Comment by 0xdevcollins** [comment]
Can I be assigned to this?

**Comment by martinvibes** [comment]
Is it okay if I tackle this?
kindly assign :)

**Comment by jaykayudo** [comment]
'I would like to take this task, I love 🍍'
ETA = 2hrs
I am a skilled python developer and i have worked on a similar task

**Comment by Akshola00** [comment]
I'd like to handle this task.

**Comment by aniruddhaaps** [comment]
@djeck1432 thanks for assigning, working right away.

**Comment by djeck1432** [comment]
@aniruddhaaps Sorry, you were unassigned, didn't manage with this task.

**Comment by od-hunter** [comment]
Can I work on this please?

**Comment by jaykayudo** [comment]
@djeck1432 i will like to work on this

**Comment by Josh-121** [comment]
Available for assignment? I like pineapple

**Comment by Benjtalkshow** [comment]
@djeck1432 , Can i take this task? I love 🍍

**Comment by Josh-121** [comment]
Mind if I try this one?
