### ISSUE TITLE
Standardize event data for withdraw event

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#233]
1.  Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. Parse data from event which fetched on-chain to humman-readable format, for example, now we have `user = data[0]` and we want to have `user = data.user`
 - In method [parse_withdrawal_event](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handler_tools/data_parser/zklend.py#L23C9-L23C31)
 - Event data structure - [event data](https://starkscan.co/event/0x03472cf7511687a55bc7247f8765c4bbd2c18b70e09b2a10a77c61f567bfd2cb_4)
3. Create Serializers model using pydantic in [serializers.py](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handler_tools/data_parser/serializers.py)
4. In method [process_withdrawal_event](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handlers/loan_states/zklend/events.py#L254)
 substitute fetching data by index `Example: user= data[0]` to `data.user` using serializer class

**Comment by Mystic-Nayy** [comment]
@djeck1432 can I please work on this?
I like 🍍

**Comment by djeck1432** [comment]
@Mystic-Nayy sorry, this task for 24 hours. not for 42, next time

**Comment by Mystic-Nayy** [comment]
> @Mystic-Nayy sorry, this task for 24 hours. not for 42, next time

Yes, I have corrected it

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other Python projects like:

- `giza-agents`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by djeck1432** [comment]
@Gerson2102, please, read guideline

**Comment by Gerson2102** [comment]
> @Gerson2102, please, read guideline

I'm reading it and I dont see the problem

**Comment by djeck1432** [comment]
@Gerson2102 You didn't read it properly, there is password which you need to apply for the issue
