### ISSUE TITLE
Standardize event data for repayment event

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#234]
1.  Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. Parse data from event which fetched on-chain to humman-readable format, for example, now we have `user = data[0]` and we want to have `user = data.user`
 - In method [parse_repayment_event](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handler_tools/data_parser/zklend.py#L33C9-L33C30)
 - Event data structure - [event data](https://starkscan.co/event/0x06fa3dd6e12c9a66aeacd2eefa5a2ff2915dd1bb4207596de29bd0e8cdeeae66_5)
3. Create Serializers model using pydantic in [serializers.py](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handler_tools/data_parser/serializers.py)
4. In method [process_repayment_event](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handlers/loan_states/zklend/events.py#L301)
 substitute fetching data by index `Example: user= data[0]` to `data.user` using serializer class

**Comment by Mystic-Nayy** [comment]
@djeck1432 can I please work on this?
I like 🍍
ETA -42hrs

**Comment by Akshola00** [comment]
hi @djeck1432 , would really love to work on this issue

**Comment by godekina** [comment]
May I take care of this?
