### ISSUE TITLE
Create test cases for error_handler

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#235]
1.Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. Create test cases for `error_hanlder` [class](https://github.com/CarmineOptions/derisk-research/blob/master/shared/error_handler/notifications.py#L17)  
 - create here folder `tests` if it's not created yet in this [folder](https://github.com/CarmineOptions/derisk-research/tree/master/shared)
4. Create positive and negative scenarios for all the class methods

**Comment by raizo07** [comment]
can I work on this?
