### ISSUE TITLE
Create event db and add crud methods + tests

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#242]
1. Read guideline our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md)
2. Create new `EventBaseModel(Base)` [here](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/db/models/event.py), [Base](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/db/models/base.py#L11)
- event_name: str, index=True
- block_number: int index=True
- protocol_id: str, index=True [ProtocolIDs choices](https://github.com/CarmineOptions/derisk-research/blob/master/shared/constants.py#L55)
5. Create in [zklend_events.py](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/db/models/zklend_events.py) new models based on pydantic fields and inherited from `EventBaseModel`
- [AccumulatorsSyncEventData](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handler_tools/data_parser/serializers.py)
- [LiquidationEventData](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handler_tools/data_parser/serializers.py#L38)
6. Create CRUD class [here](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/db/crud.py) new class
`ZkLendEventDBConnecotr(DBConnector)` with next methods:
- create_accumulator_event(protocol_id, event_name, block_number, event_data)
- create_liquidation_event(protocol_id, event_name, block_number, event_data) fields from `LiquidationEventModel`
- get_all_events(protocol_id, event_name, block_number) - filter by `protocol_id or/and event_name or/and block_number` and get all events, each parameter is not required and can be `None`
7. Create test cases for all new code. 
8. Generate migration file

**Comment by binayak9932** [comment]
i think i can work on it i have contributed to similar issue on spotnet .Btw  I love 🍍.
