### ISSUE TITLE
Create test cases LoanStateComputationBase

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#257]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. Create test cases  positive and negative  for class [LoanStateComputationBase](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/abstractions.py#L17)
3. Create test cases positive and negative for class [HashstackBaseLoanStateComputation](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/abstractions.py#L303C7-L303C40)
4. For these test cases create new folder `loan_states` and there create new file `test_loan_state_computations.py` in this [folder](https://github.com/CarmineOptions/derisk-research/tree/master/apps/data_handler/tests)

**Comment by CollinsC1O** [comment]
Could I try solving this?

**Comment by petersdt** [comment]
Could I take on this issue? I love 🍍 ETA 2day

**Comment by Kaminar-i** [comment]
I'd like to take this up, to solve, if it's fine by you.

**Comment by Kaminar-i** [comment]
I would love to work on this

**Comment by djeck1432** [comment]
@CollinsC1O @petersdt  estimation time is 24Hours

**Comment by djeck1432** [comment]
@Kaminar-i read guideline and reapply again

**Comment by djeck1432** [comment]
@petersdt you have 24 hours for this task, works for you?

**Comment by 0xdevcollins** [comment]
I would like to take this task, I love 🍍
I will make a PR in 24hrs

**Comment by mimisavage** [comment]
I’d like to work on this. I love 🍍
I will make i pr within 24hrs this is my first time working on this project

**Comment by sigmadawg** [comment]
I love 🍍 and im a newbie contributor, i would love to work on this.
Estimated timeframe : 10hrs

**Comment by suhas-sensei** [comment]
I would like to take this task, I love 🍍. I will create a new folder called loan_states and implement comprehensive test cases in test_loan_state_computations.py, covering both positive and negative scenarios for the LoanStateComputationBase and HashstackBaseLoanStateComputation classes. Hoping this would take a day, as i got used to OS here after merging one :)

**Comment by suhas-sensei** [comment]
grateful for the opportunity @djeck1432

**Comment by djeck1432** [comment]
@suhas-sensei You will be unassigned in 1.5 hours, if I won't see draft PR with good progress (not 2 lines of code)

**Comment by ikemHood** [comment]
Hey @djeck1432, I could assist with this, will create a PR before morning

**Comment by djeck1432** [comment]
@suhas-sensei time is over, sorry you are unassigned

**Comment by ikemHood** [comment]
Can I get on this @djeck1432

**Comment by od-hunter** [comment]
Hi can I work on this issue now? I’m ready to work

**Comment by Benjtalkshow** [comment]
Hi @djeck1432 
Can i be assigned to this issue. it will be my first time contributing to this project. I love 🍍.

**Comment by SailorJhay** [comment]
I would like to take this task, I love 🍍

**Comment by petersdt** [comment]
> I would like to take this task, I love 🍍ETA 2-3days 30th - 2nd nov I have experience in python and writing test for smart contracts. I would like to make this my first contribution to derisk

I sould delivery within your 24hrs timeline . kindly assign @djeck1432

**Comment by binayak9932** [comment]
Can I tackle this one? I can do this one within 24 hrs and I love 🍍

**Comment by NueloSE** [comment]
I would like to take this task, I love 🍍 kindly assign EDT <=10HRS

**Comment by djeck1432** [comment]
@SailorJhay First finally answer me on Spotnet and then apply here. texted 5 times any response, be respectful please.

**Comment by SailorJhay** [comment]
> @SailorJhay First finally answer me on Spotnet and then apply here. texted 5 times any response, be respectful please.

sorry about that, didn't pay attention to my notifications
