### ISSUE TITLE
 Save Zklend event to db

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#258]
1.  Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. Add new file `transform_events.py` [here](https://github.com/CarmineOptions/derisk-research/tree/master/apps/data_handler/handlers/events/zklend)
3. Create new class `ZkLendTransformer`
4. Parse events using [DeriskAPIConnector](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/api_connector.py#L9)
5. To get credentials, text me in DM @djeck_vorobey1
6. After fecthing event, create mapping: `event_name`:(`serializer_class`, `model_class`)
Example: `{"AccumulatorsSync":(AccumulatorsSyncEventData, AccumulatorsSyncEventData)}`  
7. Models you can find [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/db/models/zklend_events.py)
8. Serializers you can find [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/serializers.py#L7)
9. Parse appropriate events in `ZkLendTransformer` and save it to db

**Comment by CollinsC1O** [comment]
Mind if I try this one?

**Comment by Kaminar-i** [comment]
Can I be given the chance to work on this

**Comment by djeck1432** [comment]
@Kaminar-i Read GUIDELINE

**Comment by djeck1432** [comment]
@CollinsC1O READ GUIDELINE

**Comment by mayasimi** [comment]
I would like to take this task, I love 🍍 EDT 2days I am experienced with python and working with db. kindly assign me

**Comment by djeck1432** [comment]
@mayasimi You have 24 hours to create draft PR, otherwise you will be unassigned
