### ISSUE TITLE
 Write test cases for StarknetClient

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#259]
1.  Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. Create new file `test_starknet_client.py` in [tests folder](https://github.com/CarmineOptions/derisk-research/tree/master/apps/shared/tests)
3. Create positive and negative test cases for class [StarknetClient](https://github.com/CarmineOptions/derisk-research/blob/master/apps/shared/starknet_client.py#L11)

**Comment by Kaminar-i** [comment]
Can be given this to work on

**Comment by CollinsC1O** [comment]
I would like to take this task, I love 🍍

**Comment by petersdt** [comment]
Let me try this one! I love 🍍, ETA 2days

**Comment by godekina** [comment]
I would like to take this task, I love 🍍. I am a python developer with an interest in DeFi
I can deliver this task within 24 hours of being assigned, my approach to solving this will be to create test cases in the Python script that will test the StarknetClient Class and 3 of  the functions contained in it.

**Comment by djeck1432** [comment]
@petersdt 24 hours and I can assign it to you

**Comment by djeck1432** [comment]
@CollinsC1O You have 24 hours to make draft PR, otherwise this issue will be unassigned you
