### ISSUE TITLE
Write test cases For State and LoanEntity 

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#260]
1.  Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. Create new file `test_state_and_loan_entitiy.py` in [tests folder](https://github.com/CarmineOptions/derisk-research/tree/master/apps/shared/tests)
3. Create positive and negative test cases for class [State](https://github.com/CarmineOptions/derisk-research/blob/master/apps/shared/state.py#L17)
4. Create positive and negative test cases for class [LoanEntity](https://github.com/CarmineOptions/derisk-research/blob/master/apps/shared/loan_entity.py#L16)

**Comment by Kaminar-i** [comment]
hel

**Comment by petersdt** [comment]
Can I attempt this issue?I love 🍍, ETA 2days

**Comment by CollinsC1O** [comment]
I would like to take this task, I love 🍍

**Comment by godekina** [comment]
I would like to take this task, I love 🍍
I am a python developer, who loves financial data, I can deliver this task within 48 hours of being assigned.

**Comment by djeck1432** [comment]
@Kaminar-i You have 24 hours to make draft PR otherwise you will be unassigned

**Comment by Kaminar-i** [comment]
@djeck1432 I'm on it!
