### ISSUE TITLE
Add pylint workflow and fix all issues

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#262]
1.  Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. Install pylint via `poetry` 
3. Run this command in `apps` folder
```
pylint $(git ls-files 'data_handler/*.py') --disable=all --enable=C0114,C0115,C0116,C0301
```
4. Fix all issues which you will have in console
5. Add github workflow to run this command for new PR:
```
pylint $(git ls-files 'data_handler/*.py') --disable=all --enable=C0114,C0115,C0116,C0301
```

**Comment by djeck1432** [comment]
@binayak9932 sorry, it's for new comers

**Comment by Kaminar-i** [comment]
Can I be assigned this, I can start now

**Comment by djeck1432** [comment]
@Kaminar-i READ GUIDELINEEEEEEEEEEE

**Comment by mayasimi** [comment]
I would like to take this task, I love 🍍 EDT 2days I am experienced with python and this would be my first contribution the derisk project kindly assign me

**Comment by djeck1432** [comment]
@mayasimi  I will assign if you can do it during next 24 hours

**Comment by mayasimi** [comment]
@mayasimi kindly assign I will get it done in 24hrs

**Comment by Akshola00** [comment]
I’m interested in this one.

**Comment by 0xdevcollins** [comment]
Can I take care of this issue? I will deliver in 24 hrs

**Comment by djeck1432** [comment]
@0xdevcollins  Nope, this task for new comers

**Comment by vitaliypopel** [comment]
I wanna try this one, will done with it tomorrow, had an experience with workflows, thats easy. I would like to take this task, I love 🍍

**Comment by mimisavage** [comment]
Could I take over this issue? I love 🍍
I will make i pr within 24hrs this is my first time working on this project

**Comment by sigmadawg** [comment]
I love 🍍 and im a newbie contributor, i would love to work on this.
Estimated timeframe : 10hrs

**Comment by suhas-sensei** [comment]
I would like to take this task, I love 🍍. To complete the pylint implementation task, I will install pylint through poetry, execute the provided linting command in the apps folder to identify and fix documentation and line length issues, then create a GitHub workflow file that runs the same pylint command on pull requests.
Timeframe : 1 day

**Comment by sigmadawg** [comment]
thank you for assigning @djeck1432

**Comment by djeck1432** [comment]
@sigmadawg If I won't see any draft PR with good progress ( not 2 line of code or something like that) You will be unassigned in 1.5 hour
