### ISSUE TITLE
Add missing models for saving ZkLend events data into db

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#272]
1.  Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2.  Create new models for missing events [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/db/models/zklend_events.py) Don't forget to inherited from [EventBaseModel](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/db/models/event.py#L19C7-L19C21)
3. [Here you can find models and their fields](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/serializers.py)
Please, create new models for next events: 
- `RepaymentEventData`
- `DepositEventData`
- `BorrowingEventData`
- `WithdrawalEventData`
- `CollateralEnabledDisabledEventData`
4. Generate migration file
5. How to run migration you can find in `README.md`
If any blocker or issues, don't hesitate to text me in telegram: `djeck_vorobey1`

**Comment by NueloSE** [comment]
I  would like to take this task, I love 🍍, kindly assign me i would like to take on this. ETA <= 24hrs

**Comment by petersdt** [comment]
would like to take this task, I love 🍍, 

ETA 24hrs

**Comment by mimisavage** [comment]
Can I take care of this issue?  I love 🍍,

**Comment by CollinsC1O** [comment]
Can I contribute to this one? I love 🍍

**Comment by djeck1432** [comment]
@petersdt will you manage to create today draft PR, the timeline is changed, so you have a limited time to complete it.
12 hours for draft PR and 12 hours to complete it

**Comment by ikemHood** [comment]
Can I contribute to this one? I love 🍍
 i will create a pr before EOD

**Comment by binayak9932** [comment]
Could I take over this issue? i can work with it within 12 hours for draft PR and 12 hours to complete it .I love 🍍 btw also i have experience in this repo.

**Comment by petersdt** [comment]
@djeck1432. I would have been capable of handling the task. Please let me know if any other opportunities are available, as I am open to taking on task.
