### ISSUE TITLE
Add missing models to TransformZklend

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#275]
1.  Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. In this file, add the newly created models and their logic, following the same approach as was done previously with similar models.
[here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/events/zklend/transform_events.py#L48)
3. Info about mapping [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/zklend/events.py#L48)
4. List of new models [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/db/models/zklend_events.py): 
- `RepaymentEventModel`
- `DepositEventModel`
- `BorrowingEventModel`
- `WithdrawalEventModel`
- `CollateralEnabledDisabledEventModel`
5. In the end, add test cases for class `ZklendTransformer`
6. Make sure that pylint and pytest flow in github passed

**Comment by raizo07** [comment]
Hi

**Comment by binayak9932** [comment]
I am python dev and returning contributer to this project .I contributed to this project zklend_events,and crud methods .I think i can do this pretty fast .btw I love 🍍

**Comment by 0xdevcollins** [comment]
I'll like to work on this, I love 🍍

**Comment by Josh-121** [comment]
I'd love to give this a go. I love 🍍

**Comment by petersdt** [comment]
May I be assigned to this?

**Comment by Kaminar-i** [comment]
May I handle this issue?
kindly assign :)

**Comment by djeck1432** [comment]
Guys, only for new comers, it's last issues

**Comment by Kingsuite** [comment]
Could I take on this issue?

**Comment by mayasimi** [comment]
I would like to take this task, I love 🍍, kindly assign ETA 5hrs
