### ISSUE TITLE
Add test cases for ZkLendLoanEntity 

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#276]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. add new folder `data_handlers` and then inside `data_handlers` add `loan_states`. [here](https://github.com/CarmineOptions/derisk-research/tree/master/apps/data_handler/tests)
3. Create new test file `test_zklend_loan_entity` inside `loan_states` folder
4. Use this already created mock classes for it [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/tests/loan_state/test_loan_state_computations.py)
5. Add positive and negative test cases for this class [ZkLendLoanEntity](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/zklend/events.py#L70C7-L70C23)

**Comment by binayak9932** [comment]
I am python dev and returning contributer to this project .I contributed to this project .I think i can make the TC's on ZkLendLoanEntity  pretty fast .btw I love 🍍

**Comment by Josh-121** [comment]
I’d like to help with this.

**Comment by 0xdevcollins** [comment]
I'll like to work on this, I love 🍍

**Comment by TEMHITHORPHE** [comment]
Can I jump on this task?
Familiar with was is being asked.
I'll make a draft PR within the alloted time period.

**Comment by martinvibes** [comment]
I'd be happy to do this.
please kindly assign :)

**Comment by petersdt** [comment]
Can I attempt this issue?

**Comment by Kaminar-i** [comment]
Could I try solving this?
please kindly assign :)

**Comment by Kingsuite** [comment]
May I take this issue on?

**Comment by djeck1432** [comment]
@TEMHITHORPHE Please prepare during next 2 hours your draft PR, otherwise you will be unassigned

**Comment by djeck1432** [comment]
@TEMHITHORPHE You were unassigned, because I can't see any draft PR

**Comment by djeck1432** [comment]
@Kaminar-i Please, start working as soon as possible, the hackathon is going to end

**Comment by binayak9932** [comment]
@djeck1432  i can do this asap

**Comment by Kaminar-i** [comment]
@djeck1432, thank you and don't worry, I'm on the issue

**Comment by djeck1432** [comment]
@Kaminar-i  will anticipate your PR during next 4 hours

**Comment by mayasimi** [comment]
hi @djeck1432 if this task is avaliable am open to take it. ETA <= 8hrs

**Comment by Kaminar-i** [comment]
hey @djeck1432 please i'm creating a PR soon
