### ISSUE TITLE
Add test cases for ZkLendState

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#277]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
2. add new folder `data_handlers` and then inside `data_handlers` add `loan_states`. [here](https://github.com/CarmineOptions/derisk-research/tree/master/apps/data_handler/tests)
3. Create new test file `test_zklend_loan_entity` inside `loan_states` folder
4. Use this already created mock classes for it [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/tests/loan_state/test_loan_state_computations.py)
5. Create positive and negative test cases for [ZklendState](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/zklend/events.py#L161)

**Comment by binayak9932** [comment]
I am python dev and returning contributer to this project .I contributed to this project .I think i can make the TC's on  ZkLendState pretty fast .btw I love 🍍

**Comment by 0xdevcollins** [comment]
I'll like to work on this, I love 🍍

**Comment by martinvibes** [comment]
Could I take a shot at this?

**Comment by godekina** [comment]
I would like to take this task, I love 🍍I can complete this task within 48 hours of being assigned to it, I am a Python developer and I have experience in DeFi.

**Comment by petersdt** [comment]
Could I take over this issue?

**Comment by Kaminar-i** [comment]
Could I take on this issue?
please kindly assign :)

**Comment by Kingsuite** [comment]
Could I take over this issue?

**Comment by djeck1432** [comment]
@0xdevcollins Please, prepare draft PR during next 2 hours, otherwise you will be unassigned

**Comment by 0xdevcollins** [comment]
Noted ser

**Comment by djeck1432** [comment]
@0xdevcollins I know that you're working on another project as well, but please, finish first this task. thank you

**Comment by djeck1432** [comment]
@0xdevcollins You were unassigned, because I don't see any draft PR

**Comment by djeck1432** [comment]
@Kingsuite please, start working as soon as possible, HAckathon is finishing soon, so we don't have a lot of time

**Comment by Kingsuite** [comment]
@djeck1432  just seeing this will get to work now

**Comment by djeck1432** [comment]
@Kingsuite will anticipate your PR during next 4 hours

**Comment by Kingsuite** [comment]
@djeck1432 i have written some testcases currently trying to make it run kind give me some more time

**Comment by djeck1432** [comment]
@Kingsuite I don't see your draft PR, I gave you more than usually 12 hours, didn't have any message to help you resolve some issue. 1 hour then will unassign you

**Comment by Kingsuite** [comment]
@djeck1432 PR https://github.com/CarmineOptions/derisk-research/pull/280 is awaiting your review.
