### ISSUE TITLE
 Standarize event data for Nostra Alpha (parse_interest_rate_model_event, parse_debt_transfer_event)

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#284]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. reference how it was done fore `Zklend` you can find it [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/zklend.py#L17)
3. In `nostra.py`  in class [NostraDataParser](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/nostra.py#L4) finish next methods:
- [parse_interest_rate_model_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/nostra.py#L8)
- [parse_debt_transfer_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/nostra.py#L23)
4. Your task is Create serializer for each even data for those methods which you can find here:
- [process_interest_rate_model_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/nostra_alpha/events.py#L329C9-L329C42)
- [process_debt_transfer_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/nostra_alpha/events.py#L457C9-L457C36)
5. Don't forget to update `process_interest_rate_model_event` and `process_debt_transfer_event` using your serializing models

**Comment by Judah04** [comment]
@lukaspetrasek
I would like to take this task, I love orange.
I am familiar with Python programming and problem solving. I am ready to begin as soon as the task is assigned and aim to complete it within a reasonable timeframe, depending on its complexity.

**Comment by caxtonacollins** [comment]
I love orange, i will love to work on this issue

**Comment by Benjtalkshow** [comment]
Can i work on this task? This is my first time contributing to this repo, I love orange.

**Comment by SYLVIANNORUKA** [comment]
Could I try solving this?I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, Cairo and Rust. I would love to contribute to this project.

**Comment by ekumamatthew** [comment]
Is this issue still available?

**Comment by ekumamatthew** [comment]
I would like to take this task, I love orange. I am a new contributor

**Comment by djeck1432** [comment]
@JP-the-Analyst  I don't see your draft PR, you were unassigned

**Comment by emarc99** [comment]
I would like to take this task, I love orange

I have development experience with django and flask, potgresql

**Comment by djeck1432** [comment]
@emarc99 If you not create draft PR, you will be unassigned in 4 hours.

**Comment by emarc99** [comment]
Having issues with git/github, will do PR any moment....
