### ISSUE TITLE
 Standarize Event Data for mint and burn none-interest

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#285]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. reference how it was done fore `Zklend` you can find it [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/zklend.py#L17)
3. In `nostra.py`  in class [NostraDataParser](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/nostra.py#L4) finish next methods:
- [parse_non_interest_bearing_collateral_mint_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/nostra.py#L11C9-L11C57)
- [parse_non_interest_bearing_collateral_burn_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/nostra.py#L14C9-L14C57)
4. Your task is Create serializer for each even data for those methods which you can find here:
- [process_non_interest_bearing_collateral_mint_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/nostra_alpha/events.py#L359C9-L359C59)
- [process_non_interest_bearing_collateral_burn_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/nostra_alpha/events.py#L492C9-L492C59)
5. Don't forget to update `process_non_interest_bearing_collateral_mint_event` and `process_non_interest_bearing_collateral_burn_event` using your serializing models

**Comment by Benjtalkshow** [comment]
I would like to take this task, I love orange. 
My ETA is 48hr from the start ODHack but i will make first PR in the next 12hrs.

**Comment by Judah04** [comment]
@lukaspetrasek
I would like to take this task, I love orange.
I am familiar with Python programming and problem solving. I am ready to begin as soon as the task is assigned and aim to complete it within a reasonable timeframe, depending on its complexity.

**Comment by Chukwuemeka-James** [comment]
I would like to take this task, I love orange. I can get this done within 48 Hours.
To actualise this task I'll leverage my knowlegde of data analysis and object oriented programming.

**Comment by ShantelPeters** [comment]
Please can i be assigned to this issue @djeck1432 
I love oranges.

**Comment by gwachatkozah** [comment]
@djeck1432  I would like to take this task, I love orange. I am proficient in python and i aim to complete this task 72hrs after assignment. I am a new contributor

**Comment by SYLVIANNORUKA** [comment]
Could I take a shot at this?I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, Cairo and Rust. I would love to contribute to this project.

**Comment by djeck1432** [comment]
@gwachatkozah I can assign you only if task will be done during max 24hours and you will create draft PR in next 12 hours

**Comment by JP-the-Analyst** [comment]
I would like to take this task, I love orange

This task aligns with my skills and interest. The idea that comes to mind in solving this is to utilize Python programming language and leverage the Apache Beam library for data processing and standardization. I will design a data pipeline that extracts relevant data from the ZkLend event logs, applies the necessary transformations to standardize the event data, and stores the output in a suitable database format. Specifically, I will use Apache Beam's SQL-like syntax to define the data transformations and Apache Beam's built-in functions to handle data serialization and deserialization. By leveraging these tools, I'm confident that I can efficiently and accurately standardize the event data for mint and burn none-interest events. However, I am open to discussion and further clarification if a different method or logic is to be employed

**Comment by gwachatkozah** [comment]
> @gwachatkozah I can assign you only if task will be done during max 24hours and you will create draft PR in next 12 hours

okay that can be done.

**Comment by MrRoudyk** [comment]
I would like to take this task, I love orange

**Comment by ekumamatthew** [comment]
I would like to take this task, I love orange. I am a new contributor

**Comment by obacollins-lab** [comment]
I'd love to work on this!  
This is my first time contributing to this project

**Comment by ymjrcc** [comment]
Can I take this issue?

**Comment by kfastov** [comment]
Hey, may I solve this one?
On high level: The code will check which version of SNIP-9 does account support, then pack the user's call into OutsideCall, then sign it and post to AVNU API to be executed by AVNU.
About me: have been writing Cairo code for almost a year, participated in multiple ODHacks and a Hacker House

**Comment by djeck1432** [comment]
@kfastov I think you post in the wrong issue your application

**Comment by djeck1432** [comment]
@blessingbytes yeah for sure, just READ GUIDELINE

**Comment by hossamanany** [comment]
I’d love to work on this task.

**Comment by djeck1432** [comment]
@hossamanany just friendly reminder, if you not create draft PR in next 4 hours you will be unassign

**Comment by djeck1432** [comment]
@hossamanany You were unassigned from your issue

**Comment by Kaminar-i** [comment]
hey @djeck1432 please let me work on this 
i love orange

**Comment by Tzienom** [comment]
@djeck1432 I would like to take this task, I love orange

**Comment by Judah04** [comment]
@djeck1432 I would like to take this task, I love orange.
