### ISSUE TITLE
Standarize Event Data for mint and burn interest

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#286]
Standarize Event Data for mint and burn interest
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. reference how it was done fore `Zklend` you can find it [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/zklend.py#L17)
3. In `nostra.py`  in class [NostraDataParser](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/nostra.py#L4) finish next methods:
- [parse_interest_bearing_collateral_mint_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/nostra.py#L17)
- [parse_interest_bearing_collateral_burn_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/nostra.py#L20)
4. Your task is Create serializer for each even data for those methods which you can find here:
- [process_interest_bearing_collateral_mint_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/nostra_alpha/events.py#L530C9-L530C55)
- [process_interest_bearing_collateral_burn_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/nostra_alpha/events.py#L565C9-L565C55)
5. Don't forget to update `process_interest_bearing_collateral_mint_event` and `process_interest_bearing_collateral_burn_event` using your serializing models

**Comment by caxtonacollins** [comment]
@lukaspetrasek please, I would like to take this task. This is my first time contributing, I love orange

**Comment by Judah04** [comment]
@lukaspetrasek
I would like to take this task, I love orange.
Even though I am a first time contributorI am familiar with Python programming and problem solving. I am ready to begin as soon as the task is assigned and aim to complete it within a reasonable timeframe, depending on its complexity.

**Comment by Chukwuemeka-James** [comment]
I would like to take this task, I love orange. I can get this done within 48 Hours.
To actualise this task I'll leverage my knowlegde of data analysis and object oriented programming.

**Comment by ShantelPeters** [comment]
Hello @djeck1432 can i please be assigned to this issue . This would be my first contributing 
I love oranges.

**Comment by djeck1432** [comment]
@Ved-viraj Your account is suspicious; you were unassigned. Not sure if you created a new account to get this issue

**Comment by od-hunter** [comment]
> @Ved-viraj Your account is suspicious; you were unassigned. Not sure if you created a new account to get this issue, if you can explain why your account is private I will assign you back

😳😳
Hello maintainer why you say my account suspicious because my account on private? That’s not good. I see you give people issue but other maintainer do not give people so I come here and apply. It ok if you do not give me issue because you a maintainer so your choice, but don’t say Mè suspicious because me choose private.

**Comment by MrRoudyk** [comment]
Could I grab this task? My profile onlydust https://app.onlydust.com/u/MrRoudyk

**Comment by Benjtalkshow** [comment]
Can i work on this task? This is my first time contributing to this repo, I love orange.

**Comment by Unickhub** [comment]
Is it okay if I tackle this?

**Comment by Benjtalkshow** [comment]
May I take care of this? I love orange.

**Comment by ekumamatthew** [comment]
Is it okay if I take this?

**Comment by ekumamatthew** [comment]
I would like to take this task, I love orange. I am a new contributor

**Comment by ekumamatthew** [comment]
I would like to take this task, I love orange. I am a new contributor

**Comment by ekumamatthew** [comment]
I would like to take this task, I love orange. I am a new contributor

**Comment by ekumamatthew** [comment]
I would like to take this task, I love orange. I am a new contributor

**Comment by ekumamatthew** [comment]
I would like to take this task, I love orange. I am a new contributor

**Comment by ekumamatthew** [comment]
I would like to take this task, I love orange. I am a new contributor

**Comment by MrRoudyk** [comment]
I would like to take this task, I love orange
I’m interested in this one.

**Comment by djeck1432** [comment]
@Benjtalkshow  please, DO NOT SPAM, it's for new comers,

**Comment by ekumamatthew** [comment]
I would like to take this task, I love orange. I am a new contributor

**Comment by djeck1432** [comment]
@MrRoudyk you were unassigned, you didn't create draft PR with your work(empty PR doesn't count)
