### ISSUE TITLE
Standarize Event Data for mint and burn debt

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#287]
Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. reference how it was done fore `Zklend` you can find it [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/zklend.py#L17)
3. In `nostra.py`  in class [NostraDataParser](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/nostra.py#L4) finish next methods:
- [parse_debt_mint_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/nostra.py#L26)
- [parse_debt_burn_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/nostra.py#L29)
4. Your task is Create serializer for each even data for those methods which you can find here:
- [process_debt_mint_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/nostra_alpha/events.py#L600)
- [process_debt_burn_event](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/nostra_alpha/events.py#L631C9-L631C32)
5. Don't forget to update `process_debt_mint_event` and `process_debt_burn_event` using your serializing models

**Comment by godekina** [comment]
I would like to take this task, I love orange. I can deliver this project within 24 hours of being assigned to it.

**Comment by caxtonacollins** [comment]
@djeck1432 please, I would like to take this task. This is my first time contributing, I love orange. ETA 24hours

**Comment by Chukwuemeka-James** [comment]
I would like to take this task, I love orange. I can get this done within 24 Hours.
To actualise this task I'll leverage my knowlegde of data analysis and object oriented programming.

**Comment by 0xElectrifier** [comment]
Hello, I'm Electrifier, a software engineer and I would like to take this task, I love orange. I should be able to fix this in 24 hours

**Comment by djeck1432** [comment]
@0xElectrifier you have one hour to create draft PR, otherwise you will be unassigned
