### ISSUE TITLE
Create test cases for ZkLend Initializer

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#288]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create test cases(positive and negative sceanrios) for [ZkLendInitializer](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/zklend/utils.py)
3. Add these test cases to folder [loan_state](https://github.com/CarmineOptions/derisk-research/tree/master/apps/data_handler/tests/loan_state)
4. For mocking db, you can use this [one](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/tests/conftest.py)

**Comment by Michaelkingsdev** [comment]
I would like to take this task, I love orange. My ETA 24hrs. I am a new contributor.

**Comment by Judah04** [comment]
@lukaspetrasek
I would like to take this task, I love orange.
Even though I am a first time contributorI am familiar with Python programming and problem solving. I am ready to begin as soon as the task is assigned and aim to complete it within a reasonable timeframe, depending on its complexity.

**Comment by Chukwuemeka-James** [comment]
I would like to take this task, I love orange. I can get this done within 24 Hours.
To actualise this task I'll leverage my knowlegde of Object oriented programming.

**Comment by ShantelPeters** [comment]
Hi @djeck1432 i would love to work on this issue 
I love oranges

**Comment by caxtonacollins** [comment]
Can i be assigned this issue, i love orange

**Comment by jaykayudo** [comment]
Hi @djeck1432 Can i be assigned this?
I love Orange

**Comment by rogeralbp** [comment]
Hi Team, I have skills on testing in my corporate job that I will love to enhance in the open source field, my Plan to complete this issue will be check the code, understand the parameters and the output needed for all the scenarios and conclude with some comments

**Comment by amJoe-dev** [comment]
May I handle this issue? I love to make it my first contribution to this community

**Comment by KevinLatino** [comment]
I would like to take this task, I love orange

I'll create test cases for `ZkLendInitializer`, including both positive and negative scenarios. I'll add them to the `loan_state` folder. For mocking the database, I'll use the provided setup. Given my experience with test cases in pytest, I'll ensure the tests are thorough and cover all relevant edge cases.

**Comment by Aditya-040** [comment]
Can I take this issue?

**Comment by RJMadrigal** [comment]
Hi team!

I would like to get this opportunity. I am a systems engineer from Costa Rica, with experience in C#,Python, JS, Java and I am currently learning Cairo and Rust, which makes this project a great opportunity to apply and strengthen my knowledge in Cairo.

It's my first ODhack and I'm looking for my first contribution, so I'm excited to contribute and learn in this collaborative environment. 

Thank you for considering me!

**Comment by Benjtalkshow** [comment]
May I take this issue on? I love orange

**Comment by emarc99** [comment]
Would love to tackle this!
I have used python for backend and data analysis/science. Let contribute for the first time !

**Comment by Sagar-Puniyani** [comment]
I'd love to work on this!

**Comment by ekumamatthew** [comment]
I would like to take this task, I love orange. I an a new contributor

**Comment by ekumamatthew** [comment]
I would like to take this task, I love orange. I an a new contributor

**Comment by SoarinSkySagar** [comment]
I would like to take this task, I love orange

May I handle this issue @djeck1432? I'm a new contributor on derisk as I've never contributed here.

eta: 2 days

**Comment by ekumamatthew** [comment]
I would like to take this task, I love orange. I an a new contributor
