### ISSUE TITLE
Create test cases for `InitializerDBConnector`

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#289]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create test cases (positive and negative scenarios) for [InitializerDBConnector](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/db/crud.py#L390C7-L390C29)
3. Add these test cases to folder [`db_test`](https://github.com/CarmineOptions/derisk-research/tree/master/apps/data_handler/tests/db_test)
4. For mocking db, you can use this [one](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/tests/conftest.py)

**Comment by Michaelkingsdev** [comment]
I would like to take this task, I love orange. ETA 2days.
i am a new contributor

**Comment by Judah04** [comment]
@lukaspetrasek
I would like to take this task, I love orange.
Even though I am a first time contributorI am familiar with Python programming and problem solving. I am ready to begin as soon as the task is assigned and aim to complete it within a reasonable timeframe, depending on its complexity.

**Comment by djeck1432** [comment]
@Judah04 You were unassigned, you didn't create draft PR within 12 hours

**Comment by Benjtalkshow** [comment]
@djeck1432 
It is my first time contributing to this repo. Can i work on this task? I like orange.

**Comment by Kingsuite** [comment]
@djeck1432 this looks like what I worked on in the last hackathon. Can I jump on this? ETA 48 - 60hrs

**Comment by obacollins-lab** [comment]
Is it okay if I take this?
Hello there, I'm a new contributor and would like to take on this case.

**Comment by aniruddhaaps** [comment]
I'm a python developer, a new comer here and want to take up the issue and solve it right away

**Comment by baitcode** [comment]
I would like to take this task, I love orange.

Background: https://www.linkedin.com/in/batiyiv/.

I would need to create tests for:

save_debt_category
save_collateral_enabled_by_user
get_hashtack_by_loan_ids
get_zklend_by_user_ids

Seems like a task for one day. Will be done tomorrow.

**Comment by jedstroke** [comment]
I'd like to handle this task.

**Comment by jedstroke** [comment]
I would like to take this task, I love orange. ETA 1 day

**Comment by kimcascante** [comment]
'I would like to take this task, I love orange' 
I estimate this will take me around 24 to 48 hours to complete.
I'm Kimberly Cascante, a Dojo Coding member :) Looking for my first contribution.
I have experience creating test cases, for testing purposes. 
Happy to contribute!

**Comment by martinvibes** [comment]
hey @djeck1432 I would like to take this task, I love orange

ETA: <= 12

**Comment by Kaminar-i** [comment]
I would like to take this task, I love orange
please assign me :)

ETA: 12hrs

**Comment by ekumamatthew** [comment]
I would like to take this task, I love orange. I am a new contributor

**Comment by sotoJ24** [comment]
Hi Team, I love orange, Josué From Dojo coding


I will try to do it as follows

> Positive Cases

**Test getting ZkLendCollateralDebt by user ID**

**Test getting HashtackCollateralDebt by loan IDs**

**Test saving collateral enabled data**

**Test saving debt category**

> Negative Scenarios

**Test getting ZkLendCollateralDebt by user ID with no record found**

**Test getting HashtackCollateralDebt by loan IDs with no record found**

**Test saving collateral enabled data with database error**

**Test saving debt category with database error**

> Mocking and Testing Framework

I plan to use this libraries "pytest" and a mocking library like mock

Regards

**Comment by sotoJ24** [comment]
Hi Team, I love orange, Josué From Dojo coding


I will try to do it as follows

 **Positive Cases**

- Test getting ZkLendCollateralDebt by user ID

- Test getting HashtackCollateralDebt by loan IDs

- Test saving collateral enabled data

- Test saving debt category*

**Negative Scenarios**

- Test getting ZkLendCollateralDebt by user ID with no record found

- Test getting HashtackCollateralDebt by loan IDs with no record found

- Test saving collateral enabled data with database error

- Test saving debt category with database error

**Mocking and Testing Framework**

I plan to use this libraries "pytest" and a mocking library like mock

Regards

**Comment by codebestia** [comment]
Can i work on this? I am new here
I am an experienced python developer and i am really good at writing testcases

**Comment by CollinsC1O** [comment]
Let me try this one!

**Comment by Judah04** [comment]
@djeck1432 kindly give me some time i will be making a pr in 4hrs or less please dont reassign yet

**Comment by djeck1432** [comment]
@ekumamatthew text me in DM in telegram with next text:
"Hi, this test cases have been already created! Ping Ping"

**Comment by djeck1432** [comment]
@ekumamatthew you were unassigned, I don't see your draft PR

**Comment by martinvibes** [comment]
hey @djeck1432 can i help in solving this 
I would like to take this task
I love orange

**Comment by Judah04** [comment]
@djeck1432 please let me get back on this. I would like to take this task, I love orange.

**Comment by djeck1432** [comment]
closed this issue as duplicated

**Comment by djeck1432** [comment]
Closed this issues as duplicated
