### ISSUE TITLE
Create github workflow to run test for `web_app`

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#290]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
 2. Create new github workflow for running test for [`web_app`](https://github.com/CarmineOptions/derisk-research/tree/master/apps/web_app/tests)
 3. Here is the example how it was done for [`data_handler`](https://github.com/CarmineOptions/derisk-research/blob/master/.github/workflows/ci.yml)

**Comment by Benjtalkshow** [comment]
I would like to take this task, I love orange. 
My ETA is 48hr from the start ODHack but i will make first PR in the next 12hrs.

**Comment by Judah04** [comment]
@lukaspetrasek
I would like to take this task, I love orange.
Even though I am a first time contributorI am familiar with Python programming and problem solving. I am ready to begin as soon as the task is assigned and aim to complete it within a reasonable timeframe, depending on its complexity.

**Comment by Chukwuemeka-James** [comment]
I  would like to take this task, I love orange. I can get this done within 10 Hours.
To actualise this task I'll leverage my knowlegde of GitHub Action and workflow, and Docker basic.

**Comment by Immanuelolivia1** [comment]
Hey @lukaspetrasek I will like to work on this issue

**Comment by od-hunter** [comment]
I would like to take this task, I love orange
