### ISSUE TITLE
Create cron tab task for saving ZkLend event to db

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#291]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
  2. Add here new task for parsing event in normalized format and save it to db every 5 mins [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/celery_app/event_tasks.py)
  3. Use [`ZklendTransformer.run`](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/events/zklend/transform_events.py#L97C7-L97C24)
  4. Handle error cases and add log time of execution to print it out in logs

**Comment by caxtonacollins** [comment]
please, I would like to take this task, I love orange

**Comment by djeck1432** [comment]
@caxtonacollins you were unassigned, passed 12 hours and you didn't create draft PR

**Comment by Benjtalkshow** [comment]
Let me work on this @djeck1432 
I like orange
