### ISSUE TITLE
Move all events models into separated files

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#307]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create new folder `serializers` [here](https://github.com/CarmineOptions/derisk-research/tree/master/apps/data_handler/handler_tools/data_parser)
3. Move from [serializers.py](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/serializers.py) into separated files (zklend.py and nostra.py)
4. Which serializer where used you can find here:
- [`nostra`](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/nostra.py)
- [`zklend`](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/zklend.py)
5.  in `serializers` folder, create new file `__init__.py` where you will import all serializers from `zklend.py` and `nostra.py`

**Comment by Jagadeeshftw** [comment]
I would like to work on this issue

**Comment by vestor-dev** [comment]
hey @djeck1432 can i work on this 
i love orange

**Comment by akintewe** [comment]
Hello good day, i would love to work on this issue as a new contributor, 

I have some experience in python

MY ETA is 24 hours 

I love orange

Thank you :)
