### ISSUE TITLE
[Mint and Burnt] Create models for nostra events 

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#308]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create new folder `nostra_events.py` [here](https://github.com/CarmineOptions/derisk-research/tree/master/apps/data_handler/db/models)
3. Create new models based on pydantic models fields:
- [DebtMintEventData](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/serializers.py#L338C7-L338C24)
- [DebtBurnEventData](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/serializers.py#L394C7-L394C24)
4. Please inherit your new db models with [EventBaseModel](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/db/models/event.py#L19) as it was done [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/db/models/zklend_events.py)

**Comment by Jagadeeshftw** [comment]
I would like to take this task, I love orange
Estimated Delivery Timeline:
Start Date: 24-11-2024
Completion Date: 25-11-2024
I have experience creating and working with Pydantic models and integrating them into database models.
