### ISSUE TITLE
[Interest Rate and Bearing] Create db models for nostra events

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#309]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create new file if it's not existed`nostra_events.py` [here](https://github.com/CarmineOptions/derisk-research/tree/master/apps/data_handler/db/models)
3. Create new models based on pydantic models fields:
- [InterestRateModelEventData](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/serializers.py#L449C7-L449C33)
- [BearingCollateralMintEventData](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/serializers.py#L485C7-L485C37)
4. Please inherit your new db models with [EventBaseModel](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/db/models/event.py#L19) as it was done [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/db/models/zklend_events.py) 
5. Please, add also migration file, how to run migration read in [README.md](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/README.md#how-to-run-migration-command)

**Comment by petersdt** [comment]
@djeck1432, can i be assigned this task. I love orange

**Comment by estherbreath** [comment]
I am a new contributor to this project, and would like to handle this issue, please

**Comment by djeck1432** [comment]
@estherbreath  you were unassigned, you didn't manage to create draft PR within 17 hours

**Comment by obacollins-lab** [comment]
Can I handle this task?  I'm a new contributor to this project.

**Comment by MooreTheAnalyst** [comment]
Can I start working on this?
