### ISSUE TITLE
[Debt Transfer| BearingBurn] Create db models for nostra events

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#310]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create new file if it's not existed`nostra_events.py` [here](https://github.com/CarmineOptions/derisk-research/tree/master/apps/data_handler/db/models)
3. Create new models based on pydantic models fields:
- [DebtTransferEventData](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/serializers.py#L531C7-L531C28)
- [BearingCollateralBurnEventData](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/serializers.py#L567C7-L567C37)
4. Please inherit your new db models with [EventBaseModel](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/db/models/event.py#L19) as it was done [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/db/models/zklend_events.py) 
5. Please, add also migration file, how to run migration read in [README.md](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/README.md#how-to-run-migration-command)

**Comment by vestor-dev** [comment]
hey @djeck1432 can i work on this

**Comment by amJoe-dev** [comment]
Can I please be assigned this issue, I really love to work on it
