### ISSUE TITLE
Create test cases for BaseHealthRatioHandler

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#311]
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create new folder `health_ratio_tests`  [here](https://github.com/CarmineOptions/derisk-research/tree/master/apps/data_handler/tests)
3. Create positive and negative test cases for [BaseHealthRatioHandler](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/health_ratio_level/health_ratio_handlers.py#L32C7-L32C29)
4. For db mock use from [`confest.py`](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/tests/conftest.py)

**Comment by tasneemtoolba** [comment]
I would like to take this task, I love orange(that's a lie tho, i don't like orange).
I'm not sure about the estimation tbh, but like I will try to be active ask questions and all? not my first time writing in python of course

**Comment by djeck1432** [comment]
@tasneemtoolba you were unassigned, I can't see your draft PR

**Comment by obacollins-lab** [comment]
Can I handle this task?  I'm a new contributor to this project.

**Comment by vestor-dev** [comment]
hey @djeck1432 can i work on this 
i love orange

**Comment by obacollins-lab** [comment]
I'm a Python developer who is new to this project. Could I be assigned this task?
