### ISSUE TITLE
Create test cases for BaseDBLiquidableDebtDataHandler

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#312]
1. Before applying, Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create new folder `liqudation_test` [here](https://github.com/CarmineOptions/derisk-research/tree/master/apps/data_handler/tests)
3. Create positive and negative test cases for [BaseDBLiquidableDebtDataHandler](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/liquidable_debt/debt_handlers.py)
4. For mocking db connection use fixtures from [confest.py](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/tests/conftest.py)

**Comment by djeck1432** [comment]
@chigozzdevv you were unassigned, you didn't manage to create draft PR

**Comment by raizo07** [comment]
@djeck1432 can I work on this?

**Comment by OWK50GA** [comment]
@djeck1432 can I work on this

**Comment by obacollins-lab** [comment]
Can I work on this, please? I'm a new contributor to this project.

**Comment by kozah04** [comment]
I would like to take this task, I love orange. I am proficient in Python and a new contributor.
