### ISSUE TITLE
Script for saving Nostra events to db

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#321]
1. Before applying, Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create [here](https://github.com/CarmineOptions/derisk-research/tree/master/apps/data_handler/handlers/events) new folder `nostra` and then create in it `__init__.py` and `transform_events.py` 
3. Use these [models](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/db/models/nostra_events.py) to save result to db
4. Here is example, how it was done for [zklend](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/events/zklend/transform_events.py)
5. Events you can find here: https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/nostra_alpha/events.py#L161

**Comment by MrRoudyk** [comment]
I would like to take this task, I love orange
