### ISSUE TITLE
[Backend] Create new interface for get_protocols

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#332]
1. Before applying, Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create new interface for [get_prorocols](https://github.com/CarmineOptions/derisk-research/blob/master/apps/dashboard_app/helpers/loans_table.py#L9)
3. Do not forget update after creating new interface [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/dashboard_app/helpers/loans_table.py#L85)
4. Documentation about pattern which you should use in this case [here](https://refactoring.guru/design-patterns/strategy)
5. Please, create also test case for this code.

**Comment by amJoe-dev** [comment]
@djeck1432 I love to work on this

**Comment by No-bodyq** [comment]
I’d like to work on this. I like orange

**Comment by AdejareSamad** [comment]
@djeck1432 I would like to take this task, I love orange. I am a first time contributor.
