### ISSUE TITLE
[Dashboard] Create test cases for protocol stats

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#333]
1. Before applying, Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create test cases negative and positive scenarios for next functions, which you can find [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/dashboard_app/helpers/protocol_stats.py):
- `get_general_stats`
- `get_supply_stats`
- `get_collateral_stats`
- `get_debt_stats`
- `get_utilization_stats`
3. Create new folder `tests` in `dashboard_app` dir

**Comment by NowGoody** [comment]
@djeck1432 can i work on this

**Comment by AdejareSamad** [comment]
@djeck1432 I would like to take this task, I love orange. I am a first time contributor.

**Comment by Agbeleshe** [comment]
@djeck1432 
This would be nice to have as my first contribution to the spotnet draft in less than 8 hours.

**Comment by Agbeleshe** [comment]
This would be nice to have as my first contribution to the spotnet draft in less than 8 hours. I love orange
