### ISSUE TITLE
[Dashboard] Add pipeline for running test cases

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#334]
1. Before applying, Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create github pipeline for running test cases in `dashboard_app`
3. Please create one simple test file to test it using pytest
4. Feel free to check how it was done for another app, [`data_handler`](https://github.com/CarmineOptions/derisk-research/blob/master/.github/workflows/ci.yml)

**Comment by No-bodyq** [comment]
Can I take this from here? I love orange
