### ISSUE TITLE
[Dashboard_app] Add new pipeline for pylint

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#335]
1. Before applying, Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Add new github pipeline for running pylint for `dashboard_app`
3. Please, fix all issues which will pop up with adding docstring and other stuff
4. Example, how it was implemented for [`data_hanlder`](https://github.com/CarmineOptions/derisk-research/blob/master/.github/workflows/pylint.yml)

**Comment by amJoe-dev** [comment]
I i be assigned this, really love to work on it

**Comment by Joewizy** [comment]
Is this issue still available? I'm proficient in python

**Comment by No-bodyq** [comment]
Can I take care of this issue? I love orange 
It will be my first time on this repo

**Comment by Joewizy** [comment]
Hi, I've successfully added pipeline for dashboard_app
