### ISSUE TITLE
[Data_handler] Create bash script for running generating migration in one command

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#336]
1. Before applying, Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create script for generating migration using one command in `bash` 
3. Useful link to README.md
- [alembic command](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/README.md#data-migrations)
- [docker-compose commands](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/README.md#data-migrations)
4. Please, don't forget to run before generating migration `upgrade head` 
5. Attach screen that running one command will automatically generate migration file
6. Apply if you have relevant experience with alembic, will not consider contributors who wants to try yourself, attach link to repo where you worked with it

**Comment by djeck1432** [comment]
@Supa-mega did you read it?
```
Apply if you have relevant experience with alembic, will not consider contributors who wants to try yourself, attach link to repo where you worked with it
```

**Comment by vitaliypopel** [comment]
I would like to take this task, I love orange. Can help to implement bash script with required commands
