### ISSUE TITLE
[Derisk] Update documentation for all apps 

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#337]
1. Before applying, Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. In [`README.m`](https://github.com/CarmineOptions/derisk-research/blob/master/README.md) update documentation per apps:
- `dashboard_app`
- `web_app` 
- `data_handler`
3. This documentation should have anchor to another REAMDE.md in theirs folders
4. Also, add some chapter, how to run in docker each app in main `REAMDME.md`
5. If you can see that you can improve documentation in apps, please do it

**Comment by Luluameh** [comment]
Hello @djeck1432  can I be assign this

**Comment by Supa-mega** [comment]
I would like to take this task, I love orange

**Comment by Ibinola** [comment]
I would like to take this task, I love orange, I will deliver this in the next 6hours

**Comment by ONEONUORA** [comment]
Can I handle this issue pls?
