### ISSUE TITLE
[DataHandler] Add missing events to nostra transform_events

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#338]
1. Before applying, Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. In this [file](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/events/nostra/transform_events.py), add next missing events from this [file](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/serializers/nostra.py)
- `parse_interest_bearing_collateral_mint_event`
- `parse_non_interest_bearing_collateral_burn_event`
- `parse_non_interest_bearing_collateral_mint_event`
- `parse_interest_rate_model_event`
3. Event information you can find [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/loan_states/nostra_alpha/events.py#L161)
4. DB models to save you can find [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/db/models/nostra_events.py) (if some of models are missing, please add them, don't forget to add also migration file)
5. Add test cases to your code [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/tests/test_nostra_transformer.py)

**Comment by amJoe-dev** [comment]
Could I take a shot at this? like to work on it

**Comment by djeck1432** [comment]
<img width="345" alt="Screenshot 2024-11-27 at 19 52 53" src="https://github.com/user-attachments/assets/a19c644b-03f5-4c90-8922-ca0b8e6fee51">
Nope, you are returned contributor

**Comment by olisaagbafor** [comment]
'I would like to take this task, I love orange

**Comment by nora360** [comment]
I would like to take this task, I love orange

**Comment by djeck1432** [comment]
@nora360 Sorry, I won't assign you to any issues, I texted you everywhere, you just ignored me, very bad communication skill

**Comment by MrRoudyk** [comment]
I would like to take this task, I love orange
Let me handle this issue!

**Comment by nora360** [comment]
@djeck1432 , am so sorry I was actually away over 24hrs now just travelled to handled few things, and communication was difficult there. But am back to work now, am so sorry for the unreachable moments
