### ISSUE TITLE
[Dashboard App] Create test cases for DashboardDataHandler

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#339]
1. Before applying, Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create test cases for [DashboardDataHandler](https://github.com/CarmineOptions/derisk-research/blob/master/apps/dashboard_app/helpers/load_data.py) positive and negative scenarios
3. Add new folder `tests` in `dashboard_app` if it's not there 
4. Attach screenshot in your PR that all passed good.

**Comment by olisaagbafor** [comment]
I would like to take this task, I love orange
