### ISSUE TITLE
[WebApp] Add logic of web_app form to telegram

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#351]
1. Before applying, Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Duplicate logic from Frontend to telegram bot
3. Allow user to fill in form field via telegram and save it to db

**Comment by NueloSE** [comment]
@djeck1432 can i work onthis

**Comment by Teri-anric** [comment]
I would like to take this task, I love orange.

**Comment by Tzienom** [comment]
@djeck1432 I would like to take this task, I love orange
tg:Nasiru
