### ISSUE TITLE
[Web App] Create Frontend form for web_app

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#354]
1. Before applying, Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create new frontend for our form based on figma(mobile and desktop)
3. Please use bootstrap for responsive design
4. Code is here: https://github.com/CarmineOptions/derisk-research/blob/master/apps/web_app/templates/notification.html
5. Text me in DM to get access to figma and write also in your message your email

**Comment by Abeeujah** [comment]
Hi, I'm a Full Stack Developer proficient in Python and its templating framework, Can I take care of this issue?

**Comment by OWK50GA** [comment]
Hi, let me work on this. I like Cherry
