### ISSUE TITLE
Allow any token to be selected on the FE as collateral/debt

### ISSUE THREAD

**Issue by lukaspetrasek** [CarmineOptions/derisk-research#65]
The dashboard at [https://starknet.derisk.carmine.finance](https://starknet.derisk.carmine.finance) currently allows user to select predefined collateral token - debt token pairs. Allow users to select any relevant token as the collateral token and any relevant token as the debt token.

**Comment by MarekHauzr** [comment]
The relevant tokens are those that are allowed by lending protocols to be used as collateral or borrowed.

**Comment by khayss** [comment]
Can I work on this issue?

**Comment by lukaspetrasek** [comment]
Okay, assigning you @khayss 👍🏼  

@khayss Let me know if everything is clear and whether you'll be working on the issue. If you have any questions, please ask here. What is you TG handler please? 🙏🏼 

Consider joining our [TG group](https://t.me/derisk_dev).
See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

**Comment by everest275** [comment]
Can I get this issue?

**Comment by lukaspetrasek** [comment]
Sure, assigning you @everest275  👍🏼

@everest275  Let me know if everything is clear and whether you'll be working on the issue. If you have any questions, please ask here. What is you TG handler please? 🙏🏼

Consider joining our [TG group](https://t.me/derisk_dev).
See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

**Comment by everest275** [comment]
My TG handler is @everest275. This is my first time as a colaborator in open source but got a fullstack job for 1 year so I'm ready.

Can I ask any question about the proyect here?

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lukaspetrasek** [comment]
Hi, yes, ask here pls. Or on TG if needed.

**Comment by lukaspetrasek** [comment]
Hi @everest275 , is there any progress on this? Don't see any open PR yet.

**Comment by TEMHITHORPHE** [comment]
> The relevant tokens are those that are allowed by lending protocols to be used as collateral or borrowed.

Is there any particular place that information is listed? or referenced in code?

**Comment by lukaspetrasek** [comment]
Not directly. The list of tokens is data-driven. For example, here you can find the all loans under the Hashstack V0 lending protocol: [https://storage.googleapis.com/derisk-persistent-state/hashstack_v0_data/loans.parquet](https://storage.googleapis.com/derisk-persistent-state/hashstack_v0_data/loans.parquet). You can infer it from the collateral and debt. 

To obtain the loans for other protocols, just change the folder in the address, e.g. [https://storage.googleapis.com/derisk-persistent-state/zklend_data/loans.parquet](https://storage.googleapis.com/derisk-persistent-state/zklend_data/loans.parquet) for zkLend.

**Comment by lukaspetrasek** [comment]
Hi @everest275 , any progress on this?

**Comment by lukaspetrasek** [comment]
Hi @everest275 , I have to unassign you, because you're not progressing.

**Comment by adrianvrj** [comment]
Hi @lukaspetrasek can I work on this? I already have some experience with the project and I think I could solve this real quick!

**Comment by lukaspetrasek** [comment]
Hi @adrianvrj , sure! Assigning you.
