### ISSUE TITLE
Integrate Ekubo

### ISSUE THREAD

**Issue by lukaspetrasek** [CarmineOptions/derisk-research#66]
Compute available liquidity at [Ekubo](https://app.ekubo.org/) for any given token at any given price level. 

Let's choose, for example, the STRK-USDC pair and assume the current price is 2 USDC per 1 STRK. We're interested in the amounts of USDC that we'll be able to swap for STRK at Ekubo while not pushing the price by more than 5% in a scenario where the STRK price falls to, e.g., 1.9 USDC, 1.8 USDC, ... 1 USDC, etc.

**Comment by MarekHauzr** [comment]
Essentially we are asking for an "ordebook projection" of the CL AMM (Ekubo). 

Part of that is that on some specified price levels we want to know how much liquidity is between this price level and 5% below (or above).

**Comment by djeck1432** [comment]
1. @lukaspetrasek could you please write formula for computation for the total price.
2. `Get token prices` and `Get pool liquidity` [https://docs.ekubo.org/integration-guides/reference/ekubo-api/api-endpoints]
3. First task -> create class to connect to Ekubo (research which data provides by Ekubo)
4. Transform data from Ekubo.

**Comment by lukaspetrasek** [comment]
@djeck1432 
- Constant product function AMM whitepaper: https://uniswap.org/whitepaper.pdf
- Concentrated liquidity AMM whitepaper: https://github.com/Uniswap/v4-core/blob/main/docs/whitepaper-v4.pdf
