### ISSUE TITLE
ODHack: Create a stablecoin bundle that includes USDC, USDT, and DAI, assuming full liquidity between these three stablecoins

### ISSUE THREAD

**Issue by lukaspetrasek** [CarmineOptions/derisk-research#94]
"Create a stablecoin bundle that includes USDC, USDT, and DAI, assuming full liquidity between these three stablecoins.

Steps:
1) Load the data for the main chart from the Google Storage. For example, [https://storage.googleapis.com/derisk-persistent-state/v3/zklend_data/ETH-USDC.parquet](https://storage.googleapis.com/derisk-persistent-state/zklend_data/ETH-USDC.parquet) is the file for the pair ETH-USDC for zkLend. It contains price levels and the corresponding amounts of liquidable debt for the given price level. Write the loading part in a way that the source can be easily changed from the Google Storage to a local database.
2) Combine pairs with the same collateral token, e.g. ""ETH-USDC"", ""ETH-USDT"" and ""ETH-DAI"" into a single dataframe by summing both the liquidable debt and the available liquidity.
3) Add an option to display the newly created bundle on the frontend."

**Definition od Done**
The aggregation is made correctly and the code functions well and is documented, there's an option to display all 3 stablecoins in a single chart on the dashboard.

**Comment by danielcdz** [comment]
Hello! I would like to help with this one!

**Comment by everest275** [comment]
Hello! How can I contribute to this project?

**Comment by SantoshAdabala** [comment]
> "Create a stablecoin bundle that includes USDC, USDT, and DAI, assuming full liquidity between these three stablecoins.
> 
> Steps:
> 
> 1. Load the data for the main chart from the Google Storage. Write the loading part in a way that the source can be easily changed from the Google Storage to a local database.
> 2. Combine pairs with the same collateral token, e.g. ""ETH-USDC"", ""ETH-USDT"" and ""ETH-DAI"" into a single dataframe by summing both the liquidable debt and the available liquidity.
> 3. Add an option to display the newly created bundle on the frontend."
> 
> **Definition od Done** The aggregation is made correctly and the code functions well and is documented, there's an option to display all 3 stablecoins in a single chart on the dashboard.

Can I help you on this issue

**Comment by lukaspetrasek** [comment]
Hi, assigning @princeibs, because this task is quite simple and they asked first.

**Comment by princeibs** [comment]
> Hi, assigning @princeibs, because this task is quite simple and they asked first.
> 
> @princeibs Let me know if everything is clear and whether you'll be working on the issue. If you have any questions, please ask here. What is you TG handler please? 🙏🏼
> 
> Consider joining our [TG group](https://t.me/derisk_dev). See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

Sure. Everything is clear.
I'll reach out if I have any questions.
My TG handle is *prince_ibs*

**Comment by lukaspetrasek** [comment]
Hi @princeibs , is there any progress on this? Don't see any open PR yet.

**Comment by princeibs** [comment]
Still working on it. Will be creating a PR asap

**Comment by lukaspetrasek** [comment]
Hi @princeibs , did you make any progress on this?

**Comment by rishabhRsinghvi** [comment]
Hi @lukaspetrasek if @princeibs is not working on it anymore, can I do this?

**Comment by lindsaymoralesb** [comment]
Hi @lukaspetrasek I would like to help with this missing issue. It wouldn't take me more than a couple of days for the PR to be ready for review.

**Comment by lukaspetrasek** [comment]
Hi @rishabhRsinghvi , assigning you, because you've asked first. 

Let me know if everything is clear and whether you'll be working on the issue. If you have any questions, please ask here. What is you TG handler please? 🙏🏼

Consider joining our [TG group](https://t.me/derisk_dev).
See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

**Comment by rishabhRsinghvi** [comment]
@lukaspetrasek Everything is clear, I will work on it, and I have joined the TG group too.

**Comment by lukaspetrasek** [comment]
Hi @rishabhRsinghvi , any update on this?

**Comment by danielcdz** [comment]
Hello @lukaspetrasek! I contributed in the past to this project, I can help you with this issues if it gets available

**Comment by lukaspetrasek** [comment]
Hi, unassigning @rishabhRsinghvi because he didn't provide any update/PR on this for a long time. Assigning you @danielcdz , hope you're still interested!

**Comment by danielcdz** [comment]
> Hi, unassigning @rishabhRsinghvi because he didn't provide any update/PR on this for a long time. Assigning you @danielcdz , hope you're still interested!

For sure! Happy to help!
