### ISSUE TITLE
ODHack: Analyze looping across different lending protocols

### ISSUE THREAD

**Issue by lukaspetrasek** [CarmineOptions/derisk-research#95]
"Analyze looping across different lending protocols. 

Steps: 
1) Load the data on loans for all lending protocols from the Google Storage. For example, [https://storage.googleapis.com/derisk-persistent-state/zklend_data/loans.parquet](https://storage.googleapis.com/derisk-persistent-state/zklend_data/loans.parquet) is the file with loans for zkLend. It contains the information about the user, protocol, the user's collateral and debt (tokens and amounts). Write the loading part in a way that the source can be easily changed from the Google Storage to a local database.
2) Visualize the behavior of a single user across the lending protocols in a Jupyter notebook. Use the following tokens: ""ETH"", ""wBTC"", ""USDC"", ""DAI"", ""USDT"", ""wstETH"", ""LORDS"", ""STRK"", ""UNO"" and ""ZEND"". You should be able to use the visualizations to answer the following questions:
- How many users have borrowed an asset on one protocol and deposited the asset as collateral in another protocol?
- How many users have completed the loop, i.e. deposited token X as collateral, borrowed token Y, deposited Y in another protocol and borrowed X. The loop can contain more than 2 tokens and more then 2 lending protocols.
- What is the total dollar amount of tokens used in these loops? How much are the deposits multiplicated?
- Which protocols are subject to the looping behavior the most? Compare the protocols on a per token basis.
- Feel free to come up with your own questions, metrics, hypotheses and visualizations."

**Definition of Done**
The code functions well and is documented, the analysis provides meaningful outputs and answers the questions from the setup.

**Comment by muheebyusufbaba1** [comment]
I'll like to hop on this

**Comment by vibenedict** [comment]
Hi, can i jump on this issue

**Comment by danielcdz** [comment]
Hello I want to help with this one !

**Comment by estheroche** [comment]
@lukaspetrasek i can take this, kindly assign

**Comment by lukaspetrasek** [comment]
Hi, assigning @danielcdz , because this task is complex and they provided a good description of the approach and also lower estimate of the MD that would take to solve it.

@danielcdz Let me know if everything is clear and whether you'll be working on the issue. If you have any questions, please ask here. What is you TG handler please? 🙏🏼 

Consider joining our [TG group](https://t.me/derisk_dev).
See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

**Comment by danielcdz** [comment]
Hello! @lukaspetrasek Ty for the opportunity! this is mi TG: @daniel_cdz I already joined the TG group!

**Comment by lukaspetrasek** [comment]
Hi @danielcdz, perfect! Looking forward to see the results!
