### ISSUE TITLE
ODHack: Save liquidable debt data in a database

### ISSUE THREAD

**Issue by lukaspetrasek** [CarmineOptions/derisk-research#98]
"Save liquidable debt data in a database.

Steps: 
1) Load the data on loans for all lending protocols from the Google Storage. For example, [https://storage.googleapis.com/derisk-persistent-state/zklend_data/loans.parquet](https://storage.googleapis.com/derisk-persistent-state/zklend_data/loans.parquet) is the file with loans for zkLend. 
It contains the information about the user, protocol, the user's collateral and debt (tokens and amounts). Write the loading part in a way that the source can be easily changed from the Google Storage to a local database.
2) Compute the liquidable debt for any collateral token - debt token pair in the data, for any given price (use the same range of prices that is currently implemented). This is already implemented, but the code is not efficient and needs a refactor. Recycle the current code.
3) Save the data in a database."

**Definition of Done**
The code functions well, is documented and tested. The transformation is correct. The transformed data is being saved in a database.

**Comment by vibenedict** [comment]
Hi, can i jump on this issue

**Comment by gidson5** [comment]
Hy @lukaspetrasek I'll love to work on this one

**Comment by iamnovichek** [comment]
Hi, I wanna pick this one

**Comment by iamnovichek** [comment]
Just to make sure, that I'm good candidate for this task. I will do next: Load loan data from Google Storage or a local database, refactor the existing code to efficiently compute liquidable debt for given price ranges, and save the results to a database.

**Comment by lukaspetrasek** [comment]
Hi, assigning @iamnovichek , because this task is quite complex and they provided a good description of their approach.

@iamnovichek Let me know if everything is clear and whether you'll be working on the issue. If you have any questions, please ask here. What is you TG handler please? 🙏🏼 

Consider joining our [TG group](https://t.me/derisk_dev).
See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

**Comment by iamnovichek** [comment]
> Hi, assigning @iamnovichek , because this task is quite complex and they provided a good description of their approach.
> 
> @iamnovichek Let me know if everything is clear and whether you'll be working on the issue. If you have any questions, please ask here. What is you TG handler please? 🙏🏼
> 
> Consider joining our [TG group](https://t.me/derisk_dev). See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

Yes, I'll be working on this issue. Also, I've already joined your TG group.
