### ISSUE TITLE
ODHack: Add deposits to comparison tables - zklend

### ISSUE THREAD

**Issue by lukaspetrasek** [CarmineOptions/derisk-research#99]
"Add deposits to the table with loan states. ZkLend allows its users not to use some of their deposits as collateral, while other protocols automatically count every deposit as collateral. Distinguish between regular collateral and deposits which are not labeled as collateral.

Steps: 
1) The [current pipeline](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handlers/loan_states/zklend/run.py) which computes the current states of loans contains the [deposit](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handlers/loan_states/zklend/events.py#L47) variable. When saving the data to the database (loan states table), the deposits are omitted and only collateral is saved. Save deposits under a newly created `deposit` column."

**Definition of Done**
The code functions well and is documented. The data is being saved in a database.

**Comment by vibenedict** [comment]
Hi, can i jump on this issue

**Comment by Gift-Naomi** [comment]
Can I hop on this?

**Comment by danielcdz** [comment]
Hello! I would like to help with this one !

**Comment by nicosanc** [comment]
I'd like to work on this issue. This is my first time contributing to an open source issue. I think this may take me 3-5 days. I graduated last year, I studied data science and math. I have experience with Python and Cairo. I'm currently completing the Starknet Basecamp, with the intention of becoming a seasoned Cairo dev.

**Comment by lukaspetrasek** [comment]
Hi, assigning @nicosanc , because they provided a good description of the approach and @danielcdz is already assigned to another issue.

@nicosanc Let me know if everything is clear and whether you'll be working on the issue. If you have any questions, please ask here. What is you TG handler please? 🙏🏼 

Consider joining our [TG group](https://t.me/derisk_dev).
See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

**Comment by nicosanc** [comment]
Thank you for the opportunity Lukas! My TG is @nicolander. 

I'll be starting on this issue immediately. If I have questions I will post them here. Thanks!

**Comment by lukaspetrasek** [comment]
Congrats on completing this @nicosanc !
